### ISSUE TITLE
Rails 4.2 on Heroku: Dashboard page 404

### ISSUE THREAD

**Issue by RobinDaugherty** [activeadmin/activeadmin#4208] opened 2015-11-22 18:03 UTC
I've only been able to reproduce this on Heroku. Running locally in "production" environment won't reproduce it. I'm also using cancancan, and I've authorized the Dashboard page.

Using activeadmin 1.0.0pre2 (up through commit 5536b158bf0338ea54ffaa6ba7925e7da0a3a2af), Rails 4.2.4 and cancancan 1.13.1. Authorized the dashboard page using the following:

```ruby
can :read, ActiveAdmin::Page, name: "Dashboard"
```

In development, test, and production environments on my local machine, everything works perfectly. Once deployed to Heroku, the root `/admin` route and the `/admin/dashboard` route return a 404 status. Nothing further is output in the logs, even with `debug` log level set for Rails.

**Comment by RobinDaugherty** [comment] 2015-11-22 21:22
I was able to work around this bug by downgrading Rails to 4.1.14.

[Gemfile.lock with Rails 4.2.4](https://github.com/activeadmin/activeadmin/files/41156/Gemfile.lock.before.txt)
[Gemfile.lock after downgrading to Rails 4.1.14](https://github.com/activeadmin/activeadmin/files/41158/Gemfile.lock.after.txt)

**Comment by seanlinsley** [comment] 2015-11-23 00:08
It's especially odd that Heroku is the only environment that causes the bug. Can you post a skeleton app that reproduces the error?

**Comment by RobinDaugherty** [comment] 2015-12-10 22:14
Working on it...

**Comment by timoschilling** [comment] 2015-12-10 22:16
Can you post the heroku logs from one of the requests?

**Comment by seanlinsley** [comment] 2016-01-02 23:33
I'm going to close this ticket since you haven't responded. If you're still running into this issue, please post more information so we can help.

**Closed by seanlinsley** 2016-01-02 23:33 UTC
