### ISSUE TITLE
NoMethodError (undefined method `column_names' for Contact:Class):

### ISSUE THREAD

**Issue by oeil2lynx** [activeadmin/activeadmin#4716] opened 2017-01-09 10:48 UTC
Hi, 

I am trying to connect to multiple Base (PostgreSQL, MySQL & Oracle) but I have this problem when I try to read a table from Oracle : NoMethodError (undefined method `column_names' for Contact:Class):

Here is my Model : 

```
class RsvContact < ActiveRecord::Base
  self.abstract_class = true
  establish_connection :"oracle_#{Rails.env}"
  self.table_name = 'contact'
end

```

Here is my Gemfile :

```
source 'https://rubygems.org'
ruby '2.3.3'

gem 'devise-i18n'
gem 'rails-i18n'

gem 'tzinfo-data', platforms: [:mingw, :mswin]


gem 'rails', '4.1.8'



gem 'sass-rails', '~> 4.0.3'

gem 'uglifier', '>= 1.3.0'

gem 'coffee-rails', '~> 4.0.0'

gem 'jquery-rails'
gem 'chosen-rails'



gem 'turbolinks'

gem 'spring',        group: :development

gem 'activeadmin', :git => 'https://github.com/activeadmin/activeadmin.git'

gem 'inherited_resources', '~> 1.6'
gem "devise"

gem "just-datetime-picker"

gem "faker"
gem 'newrelic_rpm', '~> 3.9'

gem 'hoptoad_notifier', '2.4.11'



gem "active_admin_import" , git: "https://github.com/activeadmin-plugins/active_admin_import.git"
gem 'ruby-nmap'
gem 'activerecord-import'

gem 'responsive_active_admin'

gem 'savon', :git => 'https://github.com/savonrb/savon.git'


gem 'activeadmin-sortable', git: 'https://github.com/DynamoMTL/activeadmin-sortable.git'

gem 'delayed_job', git:'https://github.com/collectiveidea/delayed_job.git'
gem 'delayed_job_active_record', git:'https://github.com/collectiveidea/delayed_job_active_record.git'

gem 'delayed-web', git: 'https://github.com/thebestday/delayed-web.git'
gem 'delayed_job_recurring', git:'https://github.com/amitree/delayed_job_recurring.git'

gem 'daemons'

gem 'soap2r'

gem 'pg'
gem 'ruby-oci8', '~> 2.2.3'
gem 'activerecord-oracle_enhanced-adapter', '~> 1.5.0'
gem 'dbi'
gem 'mysql2', '~> 0.3.18'
gem 'bcrypt-ruby', '3.1.5', :require => 'bcrypt' # Pour RAILS 2.3.3

gem 'coffee-script-source', '~> 1.4.0'


group :development do
  gem "thin"
end


group :production do

  platforms :ruby do # linux
    gem 'unicorn'
  end
  gem 'rails_log_stdout', :git => 'https://github.com/heroku/rails_log_stdout'

  gem 'heroku-deflater'

  gem 'rails_12factor'

  gem 'rack-throttle'
  gem 'rack-cache'
end

group :development, :test do
  gem 'factory_girl_rails'
  gem 'rspec-rails', '~> 3.0.0'
  gem 'spork', '~> 1.0rc'
end

group :test do
  gem "shoulda"
  gem "shoulda-matchers"
  gem "webmock", "~> 1.11.0"
  gem "webrat"
  gem 'simplecov', :require => false
end

```

**Comment by timoschilling** [comment] 2017-01-09 11:11
please post the stacktrace of that exception

**Comment by oeil2lynx** [comment] 2017-01-09 11:15
Oups, Sorry, here it is :

```
C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-4f494073c6c0/lib/active_admin/resource.rb:101:in `resource_column_names'
C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-4f494073c6c0/lib/active_admin/order_clause.rb:19:in `to_sql'
C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-4f494073c6c0/lib/active_admin/resource_controller/data_access.rb:216:in `apply_sorting'
C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-4f494073c6c0/lib/active_admin/resource_controller/data_access.rb:58:in `block in find_collection'
C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-4f494073c6c0/lib/active_admin/resource_controller/data_access.rb:57:in `each'
C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-4f494073c6c0/lib/active_admin/resource_controller/data_access.rb:57:in `find_collection'
C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-4f494073c6c0/lib/active_admin/resource_controller/data_access.rb:42:in `collection'
inherited_resources (1.6.0) lib/inherited_resources/actions.rb:7:in `index'
C:/Ruby23/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-4f494073c6c0/lib/active_admin/resource_controller/streaming.rb:12:in `index'
actionpack (4.1.8) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.1.8) lib/abstract_controller/base.rb:189:in `process_action'
actionpack (4.1.8) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.1.8) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.1.8) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:229:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.8) lib/active_support/callbacks.rb:86:in `run_callbacks'
actionpack (4.1.8) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.1.8) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.1.8) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.1.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.1.8) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.1.8) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.1.8) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.1.8) lib/abstract_controller/base.rb:136:in `process'
actionview (4.1.8) lib/action_view/rendering.rb:30:in `process'
actionpack (4.1.8) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.1.8) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.1.8) lib/action_controller/metal.rb:232:in `block in action'
actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:50:in `call'
actionpack (4.1.8) lib/action_dispatch/journey/router.rb:73:in `block in call'
actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:678:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
hoptoad_notifier (2.4.11) lib/hoptoad_notifier/rack.rb:27:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/rack/developer_mode.rb:48:in `traced_call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
warden (1.2.6) lib/warden/manager.rb:34:in `catch'
warden (1.2.6) lib/warden/manager.rb:34:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.5.5) lib/rack/etag.rb:23:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.5.5) lib/rack/conditionalget.rb:25:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.5.5) lib/rack/head.rb:11:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/flash.rb:254:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/cookies.rb:560:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
activerecord (4.1.8) lib/active_record/query_cache.rb:36:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
activerecord (4.1.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
activerecord (4.1.8) lib/active_record/migration.rb:380:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.1.8) lib/active_support/callbacks.rb:82:in `run_callbacks'
actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/reloader.rb:73:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
railties (4.1.8) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.1.8) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.1.8) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.1.8) lib/rails/rack/logger.rb:20:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.5.5) lib/rack/runtime.rb:17:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
activesupport (4.1.8) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.5.5) lib/rack/lock.rb:17:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.1.8) lib/action_dispatch/middleware/static.rb:84:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
hoptoad_notifier (2.4.11) lib/hoptoad_notifier/user_informer.rb:12:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
railties (4.1.8) lib/rails/engine.rb:514:in `call'
railties (4.1.8) lib/rails/application.rb:144:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.5.5) lib/rack/content_length.rb:14:in `call'
thin (1.7.0) lib/thin/connection.rb:86:in `block in pre_process'
thin (1.7.0) lib/thin/connection.rb:84:in `catch'
thin (1.7.0) lib/thin/connection.rb:84:in `pre_process'
thin (1.7.0) lib/thin/connection.rb:53:in `process'
thin (1.7.0) lib/thin/connection.rb:39:in `receive_data'
eventmachine-1.2.1-x86 (mingw32) lib/eventmachine.rb:194:in `run_machine'
eventmachine-1.2.1-x86 (mingw32) lib/eventmachine.rb:194:in `run'
thin (1.7.0) lib/thin/backends/base.rb:73:in `start'
thin (1.7.0) lib/thin/server.rb:162:in `start'
rack (1.5.5) lib/rack/handler/thin.rb:16:in `run'
rack (1.5.5) lib/rack/server.rb:264:in `start'
railties (4.1.8) lib/rails/commands/server.rb:69:in `start'
railties (4.1.8) lib/rails/commands/commands_tasks.rb:81:in `block in server'
railties (4.1.8) lib/rails/commands/commands_tasks.rb:76:in `tap'
railties (4.1.8) lib/rails/commands/commands_tasks.rb:76:in `server'
railties (4.1.8) lib/rails/commands/commands_tasks.rb:40:in `run_command!'
railties (4.1.8) lib/rails/commands.rb:17:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<top (required)>'
-e:1:in `load'
-e:1:in `<main>'
```

**Comment by oeil2lynx** [comment] 2017-01-09 11:18
It looks like it does not connect to the oracle db, but I wrote a small script that works with the same parameters : 

```
require 'rubygems'
require 'active_record'

ActiveRecord::Base.establish_connection(
    :adapter=>"oracle_enhanced",
    :database=>"X.X.X.X:1521/CCC",
    :username=>"AAA",
    :password=>"AAA"
)

class RsvContact < ActiveRecord::Base
  self.table_name = "contact"
end

table_rows = Contact.where("nom_service = 'PDC FTTH'")

puts table_rows
```

**Comment by timoschilling** [comment] 2017-01-09 11:35
Please post the Contact class

**Comment by oeil2lynx** [comment] 2017-01-09 11:38
Here Is the contact Class : 

```
class Contact < ActiveRecord::Base
  self.abstract_class = true

  establish_connection :dex_development
  self.table_name = 'RSV_CONTACT'
end

```

**Comment by dmitry** [comment] 2017-01-27 11:21
Have you tried to run `Contact.column_names` from `rails c`?

**Comment by oklas** [comment] 2017-02-28 08:24
I have same issue. Rails version 5.0.1 and 5.0.2.rc1. There is no postgres gems in bundle (mysql2 only). There is no multiple base used.

I have definitely reason when problem disappear when have time-confused migrations. The middle of chain migrations was no applied and `db/schema.rb` was without some tables.
When migrations and `db/schema.rb` was put in order. Problem was disappear.

But now it suddanly appear again. I do change some thing seems not significant. I can suppose deficit memory in vm, swap is used.

Admin is simple table and simple model with no devise and some else:

``` ruby
class Admin < ApplicationRecord
  belongs_to :user
end

```

Admin.column_names from `rails c` - show same error

Also some pages of activeadmin shows:

    # lib/formtastic/inputs/base/collections.rb:90:in `collection_from_association'
    # undefined method `where' for Admin:Module
    reflection.klass.where(where_conditions)

    # lib/active_record/inheritance.rb:152:in `compute_type'
    # uninitialized constant Ticket::Customers
    raise NameError.new("uninitialized constant #{candidates.first}", candidates.first)

    # lib/active_admin/resource.rb:106:in `resource_column_names'
    # undefined method `column_names' for Admin:Module
    resource_class.column_names

@dmitry have your problem solved or some feedback?

**Comment by deivid-rodriguez** [comment] 2017-04-10 12:09
This seems like a problem with DB migrations, unrelated to AA.

**Comment by oklas** [comment] 2017-04-10 19:31
Yes that was migrations confusions arisen by git rebase operations in my case.

**Comment by deivid-rodriguez** [comment] 2017-04-22 20:06
@oeil2lynx I'm closing this since it does not seem like a problem in AA. Feel free to reopen with reproduction steps if you disagree!

**Closed by deivid-rodriguez** 2017-04-22 20:06 UTC
