### ISSUE TITLE
Throw exception when updating or creating a model which has duplicated has_many related models

### ISSUE THREAD

**Issue by sa-wa-m** [activeadmin/activeadmin#3935] opened 2015-05-07 11:36 UTC
Thank you for maintaining the awesome gem.
I had a problem with validation. (I conducted experiment based on .test-rails-apps generated with `script/local server`.)

When updating or creating a resource, uniqueness validation defined in a model doesn't work and throws exception in some situation.
Following snippets are code example which causes the exception.

``` ruby
ActiveAdmin.register User do
  permit_params :first_name, :last_name, :username, :age, accessible_apps_attributes: [:_id, :app_id, :_destroy]

  form do |fb|
    fb.has_many :accessible_apps, allow_destroy: true, new_record: true do |a|
      a.input :app_id
    end
    fb.actions
  end
end
```

``` ruby
class User < ActiveRecord::Base
  has_many :posts, foreign_key: 'author_id'
  has_many :accessible_apps, foreign_key: 'account_id'

  accepts_nested_attributes_for :accessible_apps

  def display_name
    "#{first_name} #{last_name}"
  end

end
```

``` ruby
class AccessibleApp < ActiveRecord::Base
  validates_uniqueness_of :app_id, scope: :account_id
end
```

Schema is following.

``` ruby
class CreateAccessibleApps < ActiveRecord::Migration
  def change
    create_table :accessible_apps do |t|
      t.integer :account_id
      t.integer :app_id

      t.timestamps null: false
    end
  end
end

class AddUniqueIndex2 < ActiveRecord::Migration
  def change
    add_index :accessible_apps, [:app_id, :account_id], :unique => true, :name => 'hoge_uniq_index'
  end
end
```

When I input two same app_id, I got a error screen with exception.

I found that [save_resource](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/resource_controller/data_access.rb#L159) causes the problem.
I guess that `object.save` should be called only when object is valid in [save_resource](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/resource_controller/data_access.rb#L159), because ActiveRecord.save throws exception when has_many-related objects are duplicated, although ActiveRecord.save returns false when violating simple validation. (shown in experiment in (2)). Would you mind fixing this or may I send pull-req??

(1) Stacktraces
```
SQLite3::ConstraintException - UNIQUE constraint failed: accessible_apps.app_id, accessible_apps.account_id:
  sqlite3 (1.3.10) lib/sqlite3/statement.rb:108:in `block in each'
  sqlite3 (1.3.10) lib/sqlite3/statement.rb:107:in `each'
  activerecord (4.2.1) lib/active_record/connection_adapters/sqlite3_adapter.rb:314:in `block in exec_query'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
  rack-mini-profiler (0.9.3) lib/patches/db/activerecord.rb:21:in `log_with_miniprofiler'
  activerecord (4.2.1) lib/active_record/connection_adapters/sqlite3_adapter.rb:293:in `exec_query'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/database_statements.rb:76:in `exec_insert'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/database_statements.rb:108:in `insert'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
  activerecord (4.2.1) lib/active_record/relation.rb:64:in `insert'
  activerecord (4.2.1) lib/active_record/persistence.rb:522:in `_create_record'
  activerecord (4.2.1) lib/active_record/counter_cache.rb:139:in `_create_record'
  activerecord (4.2.1) lib/active_record/locking/optimistic.rb:75:in `_create_record'
  activerecord (4.2.1) lib/active_record/attribute_methods/dirty.rb:131:in `_create_record'
  activerecord (4.2.1) lib/active_record/callbacks.rb:306:in `block in _create_record'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_create_callbacks'
  activerecord (4.2.1) lib/active_record/callbacks.rb:306:in `_create_record'
  activerecord (4.2.1) lib/active_record/timestamp.rb:57:in `_create_record'
  activerecord (4.2.1) lib/active_record/persistence.rb:502:in `create_or_update'
  activerecord (4.2.1) lib/active_record/callbacks.rb:302:in `block in create_or_update'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_save_callbacks'
  activerecord (4.2.1) lib/active_record/callbacks.rb:302:in `create_or_update'
  activerecord (4.2.1) lib/active_record/persistence.rb:120:in `save'
  activerecord (4.2.1) lib/active_record/validations.rb:37:in `save'
  activerecord (4.2.1) lib/active_record/attribute_methods/dirty.rb:21:in `save'
  activerecord (4.2.1) lib/active_record/transactions.rb:286:in `block (2 levels) in save'
  activerecord (4.2.1) lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
  activerecord (4.2.1) lib/active_record/transactions.rb:220:in `transaction'
  activerecord (4.2.1) lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
  activerecord (4.2.1) lib/active_record/transactions.rb:286:in `block in save'
  activerecord (4.2.1) lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
  activerecord (4.2.1) lib/active_record/transactions.rb:285:in `save'
  activerecord (4.2.1) lib/active_record/associations/has_many_association.rb:41:in `insert_record'
  activerecord (4.2.1) lib/active_record/autosave_association.rb:371:in `block in save_collection_association'
  activerecord (4.2.1) lib/active_record/autosave_association.rb:364:in `save_collection_association'
  activerecord (4.2.1) lib/active_record/autosave_association.rb:184:in `block in add_autosave_association_callbacks'
  activerecord (4.2.1) lib/active_record/autosave_association.rb:157:in `block in define_non_cyclic_method'
  activesupport (4.2.1) lib/active_support/callbacks.rb:432:in `block in make_lambda'
  activesupport (4.2.1) lib/active_support/callbacks.rb:228:in `block in halting_and_conditional'
  activesupport (4.2.1) lib/active_support/callbacks.rb:506:in `block in call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:506:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_create_callbacks'
  activerecord (4.2.1) lib/active_record/callbacks.rb:306:in `_create_record'
  activerecord (4.2.1) lib/active_record/timestamp.rb:57:in `_create_record'
  activerecord (4.2.1) lib/active_record/persistence.rb:502:in `create_or_update'
  activerecord (4.2.1) lib/active_record/callbacks.rb:302:in `block in create_or_update'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_save_callbacks'
  activerecord (4.2.1) lib/active_record/callbacks.rb:302:in `create_or_update'
  activerecord (4.2.1) lib/active_record/persistence.rb:120:in `save'
  activerecord (4.2.1) lib/active_record/validations.rb:37:in `save'
  activerecord (4.2.1) lib/active_record/attribute_methods/dirty.rb:21:in `save'
  activerecord (4.2.1) lib/active_record/transactions.rb:286:in `block (2 levels) in save'
  activerecord (4.2.1) lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
  activerecord (4.2.1) lib/active_record/transactions.rb:220:in `transaction'
  activerecord (4.2.1) lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
  activerecord (4.2.1) lib/active_record/transactions.rb:286:in `block in save'
  activerecord (4.2.1) lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
  activerecord (4.2.1) lib/active_record/transactions.rb:285:in `save'
  /Users/username/gitrepos/activeadmin/lib/active_admin/resource_controller/data_access.rb:159:in `block in save_resource'
  activesupport (4.2.1) lib/active_support/core_ext/object/try.rb:77:in `try!'
  activesupport (4.2.1) lib/active_support/core_ext/object/try.rb:63:in `try'
  /Users/username/gitrepos/activeadmin/lib/active_admin/callbacks.rb:79:in `block (2 levels) in define_active_admin_callbacks'
  /Users/username/gitrepos/activeadmin/lib/active_admin/resource_controller/data_access.rb:158:in `save_resource'
  /Users/username/gitrepos/activeadmin/lib/active_admin/resource_controller/data_access.rb:148:in `block in create_resource'
  activesupport (4.2.1) lib/active_support/core_ext/object/try.rb:77:in `try!'
  activesupport (4.2.1) lib/active_support/core_ext/object/try.rb:63:in `try'
  /Users/username/gitrepos/activeadmin/lib/active_admin/callbacks.rb:79:in `block (2 levels) in define_active_admin_callbacks'
  /Users/username/gitrepos/activeadmin/lib/active_admin/resource_controller/data_access.rb:147:in `create_resource'
  inherited_resources (1.6.0) lib/inherited_resources/actions.rb:33:in `create'
  actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
  rack-mini-profiler (0.9.3) lib/mini_profiler/profiling_methods.rb:106:in `block in profile_method'
  actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.1) lib/rack/etag.rb:24:in `call'
  rack (1.6.1) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.1) lib/rack/head.rb:13:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.1) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.1) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
  activerecord (4.2.1) lib/active_record/migration.rb:378:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.1) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.1) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.1) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.1) lib/rack/sendfile.rb:113:in `call'
  rack-mini-profiler (0.9.3) lib/mini_profiler/profiler.rb:276:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  rack (1.6.1) lib/rack/lock.rb:17:in `call'
  rack (1.6.1) lib/rack/content_length.rb:15:in `call'
  rack (1.6.1) lib/rack/handler/webrick.rb:89:in `service'
  /Users/username/.rbenv/versions/2.1.4/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
  /Users/username/.rbenv/versions/2.1.4/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
  /Users/username/.rbenv/versions/2.1.4/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

(2) save throws exception when violating uniquness
``` ruby
[23] pry(main)> b = Account.new(account_name: 'test', name: 'test', last_logged_in_at: Time.current.to_i, app_restricted: 1)
b = Account.new(account_name: 'test', name: 'test', last_logged_in_at: Time.current.to_i, app_restricted: 1)
=> #<Account id: nil, account_name: "test", email: nil, name: "test", role: nil, remember_token: nil, disabled: false, last_logged_in_at: 1430981938, created_at: nil, updated_at: nil, cs_role_id: nil, app_restricted: true>
[24] pry(main)> b.permitted_apps = [PermittedApp.new(app_id: 100), PermittedApp.new(app_id: 100)]
b.permitted_apps = [PermittedApp.new(app_id: 100), PermittedApp.new(app_id: 100)]
=> [#<PermittedApp id: nil, app_id: 100, account_id: nil, created_at: nil, updated_at: nil>,
 #<PermittedApp id: nil, app_id: 100, account_id: nil, created_at: nil, updated_at: nil>]
[25] pry(main)> b.save
b.save
   (0.1ms)  BEGIN
  PermittedApp Exists (0.2ms)  SELECT  1 AS one FROM `permitted_apps`  WHERE (`permitted_apps`.`app_id` = BINARY 100 AND `permitted_apps`.`account_id` IS NULL) LIMIT 1
  PermittedApp Exists (0.1ms)  SELECT  1 AS one FROM `permitted_apps`  WHERE (`permitted_apps`.`app_id` = BINARY 100 AND `permitted_apps`.`account_id` IS NULL) LIMIT 1
  SQL (5.1ms)  INSERT INTO `accounts` (`account_name`, `app_restricted`, `created_at`, `last_logged_in_at`, `name`, `updated_at`) VALUES ('test', 1, 1430981968, 1430981938, 'test', 1430981968)
  SQL (4.8ms)  INSERT INTO `permitted_apps` (`account_id`, `app_id`, `created_at`, `updated_at`) VALUES (23, 100, 1430981968, 1430981968)
  SQL (1.1ms)  INSERT INTO `permitted_apps` (`account_id`, `app_id`, `created_at`, `updated_at`) VALUES (23, 100, 1430981968, 1430981968)
Mysql2::Error: Duplicate entry '23-100' for key 'index_permitted_apps_on_account_id_and_app_id': INSERT INTO `permitted_apps` (`account_id`, `app_id`, `created_at`, `updated_at`) VALUES (23, 100, 1430981968, 1430981968)
   (0.2ms)  ROLLBACK
ActiveRecord::RecordNotUnique: Mysql2::Error: Duplicate entry '23-100' for key 'index_permitted_apps_on_account_id_and_app_id': INSERT INTO `permitted_apps` (`account_id`, `app_id`, `created_at`, `updated_at`) VALUES (23, 100, 1430981968, 1430981968)
from /Users/username/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `query'
[26] pry(main)> b.valid?
b.valid?
  PermittedApp Exists (0.3ms)  SELECT  1 AS one FROM `permitted_apps`  WHERE (`permitted_apps`.`app_id` = BINARY 100 AND `permitted_apps`.`account_id` = 23) LIMIT 1
  PermittedApp Exists (0.2ms)  SELECT  1 AS one FROM `permitted_apps`  WHERE (`permitted_apps`.`app_id` = BINARY 100 AND `permitted_apps`.`account_id` = 23) LIMIT 1
  => false
```

**Comment by andricicezar** [comment] 2015-05-21 12:02
I have this problem too.

**Comment by timoschilling** [comment] 2015-05-21 15:16
> I guess that object.save should be called only when object is valid in save_resource, because ActiveRecord.save throws exception when has_many-related objects are duplicated, although ActiveRecord.save returns false when violating simple validation.

I don't understand the difference, you write `ActiveRecord.save throws exception` and `ActiveRecord.save returns false`.

I my eyes ActiveAdmin do the same what you do in the console.

My be this is a SQLite ActiveRecord problem, while your working example (console) shows a `ActiveRecord::RecordNotUnique: Mysql2::Error: Duplicate entry` and your error example shows a `SQLite3::ConstraintException - UNIQUE constraint failed`. For my understanding `SQLite3::ConstraintException` needs to be rescued by ActiveRecord and reraised as `ActiveRecord::RecordNotUnique`, which should result in a `document.save == false`.

**Comment by andricicezar** [comment] 2015-05-21 16:46
Check this to see the problem:
https://github.com/andricicezar/error-activeadmin

**Comment by timoschilling** [comment] 2015-05-21 18:47
Have you tried your 1 test case with a MySQL or Postgre DB?

**Comment by andricicezar** [comment] 2015-05-21 19:08
Not yet. I am going to try it sunday.

**Comment by andricicezar** [comment] 2015-05-22 06:40
Same error with mysql2:
https://github.com/andricicezar/error-activeadmin

**Comment by Fivell** [comment] 2015-05-22 08:24
@andricicezar ,  the reason of that is that AR try to create nested attributes in bulk query (not one by one) after performing all validations. 

so validations 
```
 PermittedApp Exists (0.2ms)  SELECT  1 AS one FROM `permitted_apps`  WHERE (`permitted_apps`.`app_id` = BINARY 100 AND `permitted_apps`.`account_id` IS NULL) LIMIT 1
  PermittedApp Exists (0.1ms)  SELECT  1 AS one FROM `permitted_apps`  WHERE (`permitted_apps`.`app_id` = BINARY 100 AND `permitted_apps`.`account_id` IS NULL) LIMIT 1
```


And  only than inserts
```
 SQL (4.8ms)  INSERT INTO `permitted_apps` (`account_id`, `app_id`, `created_at`, `updated_at`) VALUES (23, 100, 1430981968, 1430981968)
  SQL (1.1ms)  INSERT INTO `permitted_apps` (`account_id`, `app_id`, `created_at`, `updated_at`) VALUES (23, 100, 1430981968, 1430981968)
```


What you should do is add additional validator in your User model which will check uniqueness of nested accessible_apps

**Comment by timoschilling** [comment] 2015-05-22 08:28
@andricicezar after one not problem related changes your app works for me:
`permit_params :name, relations_attributes: [:user_id, :id, :_destroy]`

The test-app works for me:
```
Started PATCH "/admin/teams/1" for ::1 at 2015-05-22 10:02:34 +0200
Processing by Admin::TeamsController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"BK6Mm8htmctL6WBDI6Mf2u+JAHz5aD4qenxREt1gyszfXIGD1mxRH7KunTgA/1lwbEMKXaPMmf+kW/aXMO9Mrg==", "team"=>{"name"=>"HackIT", "relations_attributes"=>{"0"=>{"user_id"=>"1", "_destroy"=>"0", "id"=>"1"}, "1"=>{"user_id"=>"3", "_destroy"=>"0", "id"=>"2"}, "2"=>{"user_id"=>"3"}}}, "commit"=>"Update Team", "id"=>"1"}
  AdminUser Load (0.3ms)  SELECT  `admin_users`.* FROM `admin_users` WHERE `admin_users`.`id` = 2  ORDER BY `admin_users`.`id` ASC LIMIT 1
  Team Load (0.1ms)  SELECT  `teams`.* FROM `teams` WHERE `teams`.`id` = 1 LIMIT 1
  Relation Load (0.2ms)  SELECT `relations`.* FROM `relations` WHERE `relations`.`team_id` = 1 AND `relations`.`id` IN (1, 2)
   (0.1ms)  BEGIN
  Relation Exists (0.3ms)  SELECT  1 AS one FROM `relations` WHERE (`relations`.`user_id` = BINARY 3 AND `relations`.`team_id` = 1) LIMIT 1
   (0.1ms)  ROLLBACK
  Relation Load (0.3ms)  SELECT `relations`.* FROM `relations` WHERE `relations`.`team_id` = 1
  User Load (0.1ms)  SELECT `users`.* FROM `users`
  CACHE (0.0ms)  SELECT `users`.* FROM `users`
  CACHE (0.0ms)  SELECT `users`.* FROM `users`
  CACHE (0.0ms)  SELECT `users`.* FROM `users`
  Rendered /Users/captainhagbard/Sites/rails/activeadmin/app/views/active_admin/resource/edit.html.arb (219.6ms)
Completed 200 OK in 267ms (Views: 228.0ms | ActiveRecord: 1.6ms)
```
![edit_team___activeadminbug](https://cloud.githubusercontent.com/assets/165599/7766409/49a6f312-0069-11e5-9fe9-1ae84313f62f.jpg)

But I can reproduce @sa-wa-m Problem if I use @andricicezar's App and add a index:
```ruby
add_index :relations, [:user_id, :team_id], :unique => true
```
And then creating a new record with to two times the same User.

ActiveRecord seams to don't check the uniqueness in this case.

**Comment by timoschilling** [comment] 2015-05-22 08:29
ok, @Fivell was faster (or shorter) then me ;)

Since we came both to the same result, that this is not a ActiveAdmin problem, I’m going to close this. Please feel free to update this issue with additional information so it can be reconsidered.

**Closed by timoschilling** 2015-05-22 08:29 UTC

**Comment by andricicezar** [comment] 2015-05-22 09:23
Thanks!
