### ISSUE TITLE
Namespace issues

### ISSUE THREAD

**Issue by davidwparker** [activeadmin/activeadmin#4774] opened 2017-01-31 17:04 UTC
Hello, I posted this on a related issue here:
https://github.com/activeadmin/activeadmin/issues/3960

as well on StackOverflow here:
http://stackoverflow.com/questions/41841367/multiple-namespaces-on-rails-activeadmin-issues

But have not heard anything in a week, so I'm creating a new issue.

I'm having the same issue, but I'm not able to get the app to start. 

Once I add `"namespace: "admins" do` to a subfolder's dashboard.rb, it blows up with the same error:

```
Invalid route name, already in use: 'admins_root'  (ArgumentError)
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming.
```

I've tried adding `root_to` and `root_to_options=`:
```
config.namespace :superadmin do |superadmin|
      superadmin.root_to_options= {as: "superadmin_root"}
      superadmin.root_to="dashboard#index"
end
```
```
config.namespace :admins do |admins|
      admins.root_to_options= {as: "admins_root"}
      admins.root_to="admins/dashboard#index"
end
```

But I still have the error above where it won't let me start the server.

Note that I tried other things and posted on SO before finding this issue, (http://stackoverflow.com/questions/41841367/multiple-namespaces-on-rails-activeadmin-issues)

**Comment by timoschilling** [comment] 2017-01-31 17:55
closed as double of #3960

**Comment by davidwparker** [comment] 2017-01-31 18:16
@timoschilling - I referenced #3960, which is _not_ a duplicate (I'm not changing a menu). This is a different issue entirely.

**Comment by ccallebs** [comment] 2017-02-07 15:54
@davidwparker Is this something you can reproduce on a new project? If so, can you share the configuration that causes the issue to occur?

I'd like to help, but without being able to reproduce I'd just be fumbling in the dark.

**Comment by davidwparker** [comment] 2017-02-07 17:57
@ccallebs - I'll see what I can do, thanks. Right now, it's just on my work's (closed source) AA, but I'll see if I can't copy their overall setup and reproduce the error on a new project.

**Comment by ccallebs** [comment] 2017-02-07 17:57
@davidwparker If you want to wait a bit, I'm developing a bug report template for AA. Hopefully it can help.

**Comment by davidwparker** [comment] 2017-02-07 18:07
@ccallebs - sounds good. TBH, I'm out of the country starting next week for three months on sabbatical, so I probably won't get to this until after that trip.

**Comment by Fivell** [comment] 2017-05-09 21:44
copy paste config from related SO answer
```ruby
ActiveAdmin.setup do |config|
  # == Site Title
  config.site_title = "Customize app"
  config.site_title_link = "/"    
  #Pagination
  config.default_per_page = 10

  #Here we create the moderator route
  config.load_paths = [File.expand_path('app/admin', Rails.root), File.expand_path('app/moderator', Rails.root)]

  #Always we use moderator namespace, we will have this settings.
  config.namespace :moderator do |moderator|
    moderator.site_title = "moderator Site"
    moderator.allow_comments = false
    moderator.authentication_method = false

    # Only allow to download in xml
    moderator.download_links = [:xml]
  end

  # == User Authentication
  #
  # Active Admin will automatically call an authentication
  # method in a before filter of all controller actions to
  # ensure that there is a currently logged in admin user.
  #
  # This setting changes the method which Active Admin calls
  # within the controller.
  config.authentication_method = :authenticate_admin_user!


  # == Current User
  #
  # Active Admin will associate actions with the current
  # user performing them.
  #
  # This setting changes the method which Active Admin calls
  # to return the currently logged in user.
  config.current_user_method = :current_admin_user


  # == Logging Out
  config.logout_link_path = :destroy_admin_user_session_path

  config.batch_actions = true
end
```

**Comment by Fivell** [comment] 2017-05-09 21:44
@davidwparker , since you accepted answer from SO, I'm closing this

**Closed by Fivell** 2017-05-09 21:44 UTC

**Comment by davidwparker** [comment] 2017-05-10 03:31
thanks! I forgot about this issue.
