### ISSUE TITLE
Preserve filters when creating, updating and deleting entries

### ISSUE THREAD

**Issue by alex-bogomolov** [activeadmin/activeadmin#5087] opened 2017-07-18 07:40 UTC
Hi there!

I noticed that when some entry is created, updated or deleted, the filters and pagination that were on the index page get lost. You can simulate this behavior when setting some filters, clicking "Show" near some entry and then clicking "Cancel".

Why don't we implement a feature that will keep the query and page parameters in session and then keep them after some actions are done?

**Comment by Fivell** [comment] 2017-07-19 11:23
@alex-bogomolov , try this solution https://gist.github.com/tinynumbers/5896537

**Comment by Fivell** [comment] 2017-07-19 11:24
duplicate of  #2509 ?

**Comment by alex-bogomolov** [comment] 2017-07-19 11:29
> try this solution https://gist.github.com/tinynumbers/5896537

I think it would be nice to make this behavior a default one for index pages.

**Comment by javierjulio** [comment] 2023-03-12 23:06
This duplicate was migrated to Discussions as it was a question.

**Closed** 2023-03-12 23:06 UTC
