### ISSUE TITLE
ApplicationController and Helpers are not being reloaded in Dev Env

### ISSUE THREAD

**Issue by ghost** [activeadmin/activeadmin#697] opened 2011-10-28 13:38 UTC
why is the application_controller cached?
and how can i disable this?

cheers

**Comment by krukgit** [comment] 2015-03-12 06:45
Still a problem in `1.0.0.pre1`

**Comment by chancancode** [comment] 2015-03-13 08:59
If someone can make a barebone app on github and provide the steps (manual is fine, doesn't need to be automated) to reproduce it, I can probably take a look!

**Comment by timoschilling** [comment] 2015-03-13 09:46
@chancancode here is a test app to reproduce this bug:
https://github.com/activeadmin/activeadmin_helper_reload_bug
But it should be happen in every activeadmin app too.

**Comment by timoschilling** [comment] 2015-04-08 07:55
@chancancode any updates?

**Comment by damienh** [comment] 2015-04-21 11:24
1+ on this.

**Comment by jvaill** [comment] 2015-05-03 05:29
I took a stab at fixing this! PR is linked just above. :smile:

**Comment by timoschilling** [comment] 2015-08-18 01:10
Some notes from @jvaill from #3927:

> Just quickly brainstorming, off the top of my head I can think of a few other feasible solutions:

> 1. Add the entire `lib/` directory to `ActiveSupport::Dependencies.autoload_paths` and let Rails handle autoloading and reloading. This has the disadvantage of unloading all files inside of `lib/` on each request.
> 2. Move the controllers to a `lib/controllers/` directory and add that to `ActiveSupport::Dependencies.autoload_paths`.
> 3. [See if we can use `ActiveSupport::Dependencies.explicitly_unloadable_constants` to get Rails to explicitly unload the controllers after each request.](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/dependencies.rb#L61)
> 4. ? :smile: 

> If we'd rather not shuffle files around, then looking into the third option might be worth it.

**Comment by timoschilling** [comment] 2015-08-18 01:11
@chancancode can you take a look on this problem with the test app?
https://github.com/activeadmin/activeadmin_helper_reload_bug
Take a look on the readme
But it should be happen in every activeadmin app too.

**Comment by lakim** [comment] 2016-02-18 09:30
There is a very interesting rails issue on how the controllers are supposed to be loaded in gems like AA:
https://github.com/rails/rails/issues/12195

**Comment by seanlinsley** [comment] 2016-02-29 04:57
Disconnecting this from the Rails reloading, I can reproduce by simply calling [`ActiveAdmin.unload!`](https://github.com/activeadmin/activeadmin/blob/f7483e3b8fcd74437b03c18fb658dac62a9fc62e/lib/active_admin/application.rb#L197)
```ruby
ObjectSpace.each_object(ActiveAdmin::Resource).count => 17

ActiveAdmin.unload!

ObjectSpace.each_object(ActiveAdmin::Resource).count => 17
ids = ObjectSpace.each_object(ActiveAdmin::Resource).map{ |r| r.controller.object_id }
ids.count                                            => 17

GC.start

ObjectSpace.each_object(ActiveAdmin::Resource).count => 0
ids.count{ |id| ObjectSpace._id2ref id rescue nil }  => 17
ActiveAdmin::BaseController.descendants.count        => 22

ObjectSpace._id2ref(ids.first).name.constantize
-> NameError: uninitialized constant Admin::UsersController
```

Unload currently does [a lot of work](https://github.com/activeadmin/activeadmin/blob/f7483e3b8fcd74437b03c18fb658dac62a9fc62e/lib/active_admin/namespace.rb#L194) to remove the objects from memory, but there must be a reference to the controller somewhere that's not being removed. If only Ruby made it easy to see the references keeping an object in memory...

**Comment by seanlinsley** [comment] 2016-02-29 05:09
Well the Mass gem isn't reporting any references.
```ruby
ids = ObjectSpace.each_object(ActiveAdmin::Resource).map{ |r| r.controller.object_id }
Mass.references Mass[ids.first]
 => {"ActiveAdmin::Resource#70279696346980"=>["@controller"]} 

ActiveAdmin.unload!

Mass.references Mass[ids.first]
 => {}

**Comment by seanlinsley** [comment] 2016-02-29 05:41
This didn't seem to help:
```ruby
ActiveSupport::Dependencies.explicitly_unloadable_constants << 'ActiveAdmin::BaseController'

**Comment by glebtv** [comment] 2018-09-20 08:41
Might be related - rails code reloading becomes slower with each reload, when anything is present in app/admin folder

To reproduce:
```
 100.times { puts Benchmark.measure { reload! } }
```

For one app I have, with 100+ activeadmin modules, it is 2s for first reload, 4s for second, and up to 2-3 minutes to complete hang in 10-15 reloads.

**Comment by mvoropaiev** [comment] 2019-03-13 09:38
@glebtv not sure if this is the right issue to report, but i am experiencing the same issue with AA 1.4.3, rails 5.2.2.
Forced to re-start rails app after a few changes while developing admin part of application or otherwise it becomes unusable.
Is there something that can be done to address it? Thanks.

**Comment by deivid-rodriguez** [comment] 2019-03-13 09:48
No news here, but I've seen several development environment memory leaks fixed in Rails recently, so maybe Rails 6 brings new hope here.

In particular, there's https://github.com/rails/rails/issues/32892 and a related open PR. It'd be good if some hitting this problem could try that patch!

**Comment by mvoropaiev** [comment] 2019-03-26 14:07
Trying a patch from merged PR https://github.com/rails/rails/pull/31442/files indeed increased reload speed of application, but now activeadmin does not reloads in dev env on files (`app/admin/*`) change, changes respected only after server restart, any idea where to dig regards this?
Thanks!

**Comment by kaneru** [comment] 2019-12-18 03:37
Hello, everyone! Facing this issue in my project. Really need to DRY my code in some AA views with helpers. Is there any temporary hack for this issue? This hack seems not to work for me:

> To update your helpers automatically, you can temporary hack it like:
> 
> ```ruby
> Dir["#{ Rails.root }/app/helpers/*.rb"].each { |file| require file }
> ```

**Comment by sethdeckard** [comment] 2021-08-23 15:53
Given the age of this bug, I'm assuming this may not ever be fixed. What is a good alternative approach to using helpers in AA these days?

**Comment by ndbroadbent** [comment] 2022-07-15 04:23
I just ran into this as well, and was wondering why I had to restart my server after any change in my helper file. I was just wondering if this is easier now with Zeitwerk and Rails 6 / Rails 7?

**Comment by rogerkk** [comment] 2022-11-02 14:03
I still have to restart when i make changes to helpers, even under Zeitwerk on Rails 6.

**Closed** 2023-03-12 22:22 UTC
Labels: bug, class reloading, awaiting developer action

**Comment by javierjulio** [comment] 2023-12-16 03:08
The default branch is ready for a v4 release so I would be very open to these type of changes, I’m just not familiar with Rails autoloading to know what’s safe. I’ve been developing the new version of ActiveAdmin so I’ve experienced the pain of having to restart the dev server when making any changes. Since I've extracted partials I’ve had much better success. I would love to do the same with controllers or other files. If you’d like to help please let me know.

**Comment by jaynetics** [comment] 2024-06-17 08:18
putting this in an initializer is a bit hacky but does the trick as a workaround.

```ruby
Rails.application.reloader.to_prepare do
  Arbre.send(:remove_const, :Context)
  load $LOADED_FEATURES.grep(%r{/arbre/context\.rb}).sole
  Arbre::Context.prepend(MyHelper)
end
```
