### ISSUE TITLE
Batch actions not work with jquery3 and without turbolinks and jquery-migrate3.0

### ISSUE THREAD

**Issue by krim** [activeadmin/activeadmin#4915] opened 2017-04-18 09:14 UTC
I use:
active_admin from master
rails 5.0.2
jquery-rails 4.3.1
jquery-ui-rails 5.0.5

In this case batch actions not working at all(batch action button disabled, "all checkbox" not work).
When i add turbolinks - batch actions start to work, but confirm message failed with exception:
"elem.getClientRects is not a function" (https://github.com/jquery/jquery/issues/3157)
When i add https://code.jquery.com/jquery-migrate-3.0.0.min.js - all works fine.

**Comment by varyonic** [comment] 2017-04-18 15:05
See related discussion in #4478.

**Comment by Fivell** [comment] 2017-04-24 23:21
https://github.com/jquery/jquery/issues/3157#issuecomment-227545073

**Comment by Fivell** [comment] 2017-04-25 08:01
@varyonic , +1 for closing since it can be fixed by including https://code.jquery.com/jquery-migrate-3.0.0.min.js

**Comment by deivid-rodriguez** [comment] 2017-04-25 12:20
Mmmm, but if it's our JS that's not compatible to JQuery 3, shouldn't we migrate it or include jquery-migrate ourselves?

**Comment by Fivell** [comment] 2017-04-25 13:11
@deivid-rodriguez , I think better option is to refactor js to adopt it for jquery3 but now sure if it is hight priority for us.

**Comment by vill** [comment] 2017-05-20 04:34
I fix it so in the `app/assets/javascripts/active_admin.js.coffee`:

```
#= require jquery2
#= require active_admin/jquery_ui
#= require jquery_ujs
#= require_self
#= require active_admin/lib/batch_actions
#= require active_admin/lib/checkbox-toggler
#= require active_admin/lib/dropdown-menu
#= require active_admin/lib/flash
#= require active_admin/lib/has_many
#= require active_admin/lib/modal_dialog
#= require active_admin/lib/per_page
#= require active_admin/lib/table-checkbox-toggler
#= require active_admin/ext/jquery-ui
#= require active_admin/ext/jquery
#= require active_admin/initializers/batch_actions
#= require active_admin/initializers/datepicker
#= require active_admin/initializers/filters
#= require active_admin/initializers/tabs

@ActiveAdmin = {}
```

instead of this:

```
#= require active_admin/base
```

**Comment by varyonic** [comment] 2017-05-20 12:53
You are saying this should work?
```diff
diff --git a/app/assets/javascripts/active_admin/base.js.coffee b/app/assets/javascripts/active_admin/base.js.coffee
index 6f184ca..4254712 100644
--- a/app/assets/javascripts/active_admin/base.js.coffee
+++ b/app/assets/javascripts/active_admin/base.js.coffee
@@ -1,4 +1,4 @@
-#= require jquery
+#= require jquery2
 #= require ./jquery_ui
 #= require jquery_ujs
 #= require_self
@@ -6,4 +6,4 @@
 #= require_tree ./ext
 #= require_tree ./initializers

-window.ActiveAdmin = {}
+@ActiveAdmin = {}
```

**Comment by vill** [comment] 2017-05-20 14:02
@varyonic This is the contents of the file in my project:

`MY_PROJECT/app/assets/javascripts/active_admin.js.coffee`

```
#= require jquery2
#= require active_admin/jquery_ui
#= require jquery_ujs
#= require_self
#= require active_admin/lib/batch_actions
#= require active_admin/lib/checkbox-toggler
#= require active_admin/lib/dropdown-menu
#= require active_admin/lib/flash
#= require active_admin/lib/has_many
#= require active_admin/lib/modal_dialog
#= require active_admin/lib/per_page
#= require active_admin/lib/table-checkbox-toggler
#= require active_admin/ext/jquery-ui
#= require active_admin/ext/jquery
#= require active_admin/initializers/batch_actions
#= require active_admin/initializers/datepicker
#= require active_admin/initializers/filters
#= require active_admin/initializers/tabs

@ActiveAdmin = {}
```

This is equivalent to writing as far as I know, just short:

```
window.ActiveAdmin = {}
```

```
@ActiveAdmin = {}
```

I just changed the version of jQuery:

```
#= require jquery2
```

See more [here](https://github.com/rails/jquery-rails#installation)

**Comment by varyonic** [comment] 2017-05-22 13:29
jquery2 [works](https://travis-ci.org/varyonic/activeadmin/builds/234604411) but jquery3 [does not](https://travis-ci.org/varyonic/activeadmin/builds/234667680). The [jQuery3 release note](http://blog.jquery.com/2016/06/09/jquery-3-0-final-released/) recommends using jquery-migrate-3 to identify and resolve the breaking changes.

**Comment by javierjulio** [comment] 2017-07-05 04:26
Closing out as we are now tracking this in #5047. The real issue is not our JS code but believe it or not jQuery UI haha. Since it hasn't been updated, its not working with jQuery 3. I've comments by their maintainers to use the migrate plugin to resolve them and I've confirmed it works. The bigger picture for us is to ditch jQuery UI and replace it with our own JS.

**Closed by javierjulio** 2017-07-05 04:26 UTC
Labels: workaround
