### ISSUE TITLE
 `action_item :only` broken in version `2.0.0.rc1`

### ISSUE THREAD

**Issue by manubete** [activeadmin/activeadmin#5744] opened 2019-04-15 19:38 UTC
### Expected behavior

When I upgraded activeadmin from `1.4.2` to `2.0.0.rc1`, I expected our code to be backwards compatible and not error out on previously used functions and methods.

### Actual behavior

Before I upgraded activeadmin, our calls to certain `action_item`'s were only being called on the show page of a particular resource (say resource.id = 3). Below is a code snippet as an example

```
action_item :only => :show, :if => proc { resource.medium.sms? && !(current_admin_user.role == 'mod') } do
    link_to 'Get Incoming sms resource', show_incoming_text_messages_admin_device_path, :method => :get
  end
```

However, after the upgrade to version `2.0.0.rc1` our code started triggering this action item when one runs the index pages as well. This seems to break the routing on the index, and gives us this error :

`No route matches {:action=>"show_incoming_text_messages", :controller=>"admin/devices"} missing required keys: [:id]`

This call was not happening or erroring before the upgrade. Was this an intentional change on the new versions? Is there something else that might be happening?

### How to reproduce

Upgrade active admin to version `2.0.0.rc1` in a code repository that uses similar snippets and run locally

**Comment by deivid-rodriguez** [comment] 2019-04-23 11:22
Hi @manubete, thanks for reporting this. Can you try 2.0.0.rc2 and see if it fixes it? Thanks!

**Comment by deivid-rodriguez** [comment] 2019-04-24 04:17
This sounds like a duplicate of #5745: you need to pass a name argument to `action_item`. Let me know if this is not the case and this issue is actually different.

**Closed by deivid-rodriguez** 2019-04-24 04:17 UTC

**Comment by stephenh** [comment] 2019-04-24 14:30
@deivid-rodriguez yep, we came to the same diagnosis yesterday; apologies for not updating the ticket sooner. Thanks again!

**Comment by deivid-rodriguez** [comment] 2019-04-24 14:48
No problem, thanks for following up! :+1:
