### ISSUE TITLE
How to Activate in Two Stages

### ISSUE THREAD

**Issue by liurui12w** [activeadmin/activeadmin#5729] opened 2019-04-10 08:55 UTC
### How to Activate in Two Stages

I have a School and a teacher 's model.I want to choose a drop-down school. The teacher's second-level lower-level Larry shows that it belongs to the higher-level school.

**Comment by Fivell** [comment] 2019-04-26 12:00
duplicate of #2440

**Closed** 2019-04-28 12:13 UTC

**Comment by nicobrenner** [comment] 2021-01-07 02:43
I would say this is not a duplicate of #2440, as the functionality can be implemented without using any JS, and #2440 was explicitly closed because of proposing a JS-based solution.

One potential solution is to submit the first filter and then use that selection to render the second filter options. I've been looking for a way to do that unsuccessfully as I can't seem to access the params or selection from the first filter in the arguments to the collection option of the second filter.

Any help would be very much appreciated.

**Comment by nicobrenner** [comment] 2021-01-07 03:04
Using the solution from this stackoverflow question: https://stackoverflow.com/questions/40944075/how-can-i-show-active-admin-filters-depending-of-controller-params

I was able to get it to work:

For the case of @liurui12w it would be something like:

```ruby
before_filter :only => :index do
    @selected_school_teachers = School.active
    if params[:q].present? && [:school_id_in].present?
      @selected_school_teachers = @selected_school_teachers
                                      .where(company: params[:q][:school_id_in])
    end
    @selected_school_teachers = @selected_school_teachers.order(name: :asc)
  end

filter :school_id_in, as: :select, collection: School.active.order(name: :asc), label: "School"
filter :teacher_id_in, as: :select, collection: proc { @selected_school_teachers }, label: "Teacher"
```

Adding some keywords for anyone looking for something like this in the future:

active admin params from controller
active admin access params
active admin dynamic filter
active admin linked filters
active admin "selected option"

**Comment by liurui12w** [comment] 2021-01-07 03:07
Thank you. Thank you very much for your comments




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "☺ Nico"<notifications@github.com&gt;; 
发送时间: 2021年1月7日(星期四) 中午11:04
收件人: "activeadmin/activeadmin"<activeadmin@noreply.github.com&gt;; 
抄送: "jason"<978851037@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [activeadmin/activeadmin] How to Activate in Two Stages (#5729)





 
Using the solution from this stackoverflow question: https://stackoverflow.com/questions/40944075/how-can-i-show-active-admin-filters-depending-of-controller-params
 
I was able to get it to work:
 
For the case of @liurui12w it would be something like:
 before_filter :only =&gt; :index do     @selected_school_teachers = School.active     if params[:q].present? &amp;&amp; [:school_id_in].present?       @selected_school_teachers = @selected_school_teachers                                       .where(company: params[:q][:school_id_in])     end     @selected_school_teachers = @selected_school_teachers.order(name: :asc)   end filter :school_id_in, as: :select, collection: School.active.order(name: :asc), label: "School" filter :teacher_id_in, as: :select, collection: proc { @selected_school_teachers }, label: "Teacher"
 
Adding some keywords for anyone looking for something like this in the future:
 
active admin params from controller
 active admin access params
 active admin dynamic filter
 active admin linked filters
 active admin "selected option"
