### ISSUE TITLE
optional belongs_to for renamed active_admin resources creates incorrect url helpers

### ISSUE THREAD

**Issue by senid231** [activeadmin/activeadmin#3647] opened 2014-11-24 12:25 UTC
this code will raise exception

``` ruby
ActiveAdmin.register RegionCity, as: 'City' do
  belongs_to :country, parent_class: RegionCountry, optional: true
  navigation_menu :default
```

if belongs_to is optional url helpers are created with use of polymorphic_path and polymorphic_link methods.
This methods don't know anything about resource renaming in active admin.
when trying to open "/admin/countries/3/cities" we get:

```
undefined method `new_admin_region_country_region_city_path' for Admin::CitiesController
```

i think activeadmin need to override polymorphic_path method

I created small test project that shows this error:
https://github.com/senid231/activeadmin_test_belongs_to

**Comment by timoschilling** [comment] 2015-07-14 08:40
Is this issue still up to date?

**Comment by senid231** [comment] 2015-07-14 09:00
yes

**Comment by Fivell** [comment] 2017-02-22 21:25
@senid231 , what about bug-report ? 😺

**Comment by senid231** [comment] 2017-02-23 13:55
[Here you go](https://gist.github.com/senid231/0dcfc8b89eb0234ba5cb5ac66fec5be7)
```
I, [2017-02-23T15:53:44.588376 #21612]  INFO -- : Started GET "/admin/regions" for 127.0.0.1 at 2017-02-23 15:53:44 +0200
I, [2017-02-23T15:53:44.590438 #21612]  INFO -- : Processing by Admin::RegionsController#index as HTML
D, [2017-02-23T15:53:44.607693 #21612] DEBUG -- :   City Load (0.1ms)  SELECT "cities".* FROM "cities"  ORDER BY "cities"."id" desc
D, [2017-02-23T15:53:44.608219 #21612] DEBUG -- :   City Load (0.1ms)  SELECT  "cities".* FROM "cities"  ORDER BY "cities"."id" desc LIMIT 30 OFFSET 0
I, [2017-02-23T15:53:44.608681 #21612]  INFO -- :   Rendered /home/senid/.rvm/gems/ruby-2.2.4@tmp/bundler/gems/activeadmin-d75bbca61925/app/views/active_admin/resource/index.html.arb (15.3ms)
I, [2017-02-23T15:53:44.608795 #21612]  INFO -- : Completed 500 Internal Server Error in 18ms
F, [2017-02-23T15:53:44.610976 #21612] FATAL -- : 
ActionView::Template::Error (undefined method `new_admin_city_path' for #<Admin::RegionsController:0x007f623010ec28>):
    1: insert_tag renderer_for(:index)
  actionpack (4.2.7) lib/action_dispatch/routing/polymorphic_routes.rb:220:in `polymorphic_method'
  actionpack (4.2.7) lib/action_dispatch/routing/polymorphic_routes.rb:134:in `polymorphic_path'
  actionpack (4.2.7) lib/action_dispatch/routing/polymorphic_routes.rb:161:in `polymorphic_path_for_action'
  actionpack (4.2.7) lib/action_dispatch/routing/polymorphic_routes.rb:149:in `new_polymorphic_path'
  inherited_resources (1.7.0) lib/inherited_resources/url_helpers.rb:223:in `new_resource_path'
  actionpack (4.2.7) lib/abstract_controller/helpers.rb:67:in `new_resource_path'
  arbre (1.1.1) lib/arbre/element.rb:180:in `method_missing'
  /home/senid/.rvm/gems/ruby-2.2.4@tmp/bundler/gems/activeadmin-d75bbca61925/lib/active_admin/resource/action_items.rb:68:in `block in add_default_new_action_item'
```

**Comment by Fivell** [comment] 2017-02-25 08:54
@senid231 , why are you using ```parent_class``` option in this case? https://gist.github.com/senid231/0dcfc8b89eb0234ba5cb5ac66fec5be7#file-aa_optional_belongs_to_bug_report-rb-L92

**Comment by senid231** [comment] 2017-02-27 15:47
I updated gist for more correct reproducing

by the way it will be cool to have possibility override how `belongs_to` will find AR relations
something like:

```ruby
class Country < ActiveRecord::Base
  has_many :cities
end

class City < ActiveRecord::Base
  belongs_to :country
end

ActiveAdmin.register Country, as: 'Area' do
end

ActiveAdmin.register City, as: 'Region' do
  belongs_to :area, optional: true, parent_relation: :country, children_relation: :cities
  navigation_menu :default

  sidebar 'Area', if: proc { assigns[:area].present? } do
    attributes_table_for assigns[:area] do
      row(:id) { auto_link assigns[:area] }
      row :name
      row :iso
    end
  end

end
```

**Comment by Fivell** [comment] 2017-02-28 00:02
@senid231 , can you bring an example where ```children_relation``` option is needed?

**Comment by senid231** [comment] 2017-02-28 07:52
@Fivell you can see example in [above comment](https://github.com/activeadmin/activeadmin/issues/3647#issuecomment-282757983)
`children_relation` needed when we want children page name to be different from association name in parent model
If we remove `children_relation` from 
```ruby
ActiveAdmin.register City, as: 'Region' do
  # belongs_to :area, optional: true, parent_relation: :country, children_relation: :cities
  belongs_to :area, optional: true, parent_relation: :country
end
```
we have to rename association like this
```ruby
class Country < ActiveRecord::Base
  # has_many :cities
  has_many :regions, class_name: 'City'
end
```
And this will affect other code that not related to AA pages

**Comment by ndbroadbent** [comment] 2018-09-20 09:27
I've run into this issue so many times over the last few years, and just ran into it again. I'm going to try to fix it and send a PR

**Comment by ndbroadbent** [comment] 2018-09-20 11:30
Starting to get somewhere. In [lib/active_admin/resource/naming.rb](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/resource/naming.rb#L5-L15), `resource_name` returns an instance of `ActiveAdmin::Resource::Name` with the correct `route_key` (using the `as` option.)

However, the problem is in the `polymorphic_path` method from [actionpack/lib/action_dispatch/routing/polymorphic_routes.rb](https://github.com/rails/rails/blob/fc5dd0b85189811062c85520fd70de8389b55aeb/actionpack/lib/action_dispatch/routing/polymorphic_routes.rb#L125). It's being called with `[ "admin", <Model> ]`, and Rails calls `model.model_name`, which returns an instance of `ActiveModel::Name` based on the model. This doesn't know anything about the `as` option, so the `route_key` is incorrect.

The problem is that overriding `<Model>#model_name` could break the Rails application in other places. We only want to return an `ActiveAdmin::Resource::Name` within the active admin context, and the rest of the Rails app should use the normal `ActiveModel::Name`.

Instead of using the actual Rails model in the helper, I think we need to send in an `ActiveAdmin::Resource` that returns the correct `model_name`. Not too sure how to do that yet.

I think the problem is coming from [inherited_resources](https://github.com/activeadmin/inherited_resources/blob/master/lib/inherited_resources/url_helpers.rb#L221-L236). I've put a breakpoint in that metaprogramming and tried to figure out what was going on. Turns out that `#{prefix}#{segments}_path(#{ivars})` becomes `polymorphic_path(["admin", (given_args.first || parent), (@_resource_class_new ||= resource_class.new)].compact, given_options)`, and `resource_class.new` produces the actual Rails model instead of an ActiveAdmin resource.

So I think the fix involves somehow changing `resource_class.new.model_name` into `active_admin_resource_for(resource_class).resource_name`.

**Comment by ndbroadbent** [comment] 2018-09-20 21:10
Fixed in #5483

**Comment by Kris-LIBIS** [comment] 2019-05-23 10:48
Hi Any chance on this fix making it into a release? I got bitten by exactly the same issue.

**Comment by Kris-LIBIS** [comment] 2019-05-23 15:49
I forked myself and patched with @ndbroadbent 's fix, but alas it does not work 100%. It fixes the case

    ActiveAdmin.register User
    ActiveAdmin.register Blog::Post, as: 'Post' do
      belongs_to :user, optional: true
    end

But it still generates the wrong path in this case:

    ActiveAdmin.register Blog::User, as: 'User'
    ActiveAdmin.register Post do
      belongs_to :user, parent_class: Blog::User, optional: true
    end

And I have no clue how to fix it, nor how to write a test case for it.

**Comment by Kris-LIBIS** [comment] 2019-06-13 11:03
OK, I have rewritten the fix to make it more generic and fix the path name for any known resource in the path chain. I also managed to update the tests to test the use case above and they now pass.

The only thing I'm not sure about is how I look up the renamed resource name. There may be a more efficient way to do that, but I am not so familiar with the details and internals of Rails and ActiveAdmin. If anybody can have a look and suggest improvements, I can turn my fork into a pull request: https://github.com/Kris-LIBIS/activeadmin

**Closed** 2019-08-19 20:11 UTC
Labels: bug?, help wanted
