### ISSUE TITLE
Boolean filter not working

### ISSUE THREAD

**Issue by 8vius** [activeadmin/activeadmin#5318] opened 2018-01-15 20:03 UTC
I'm trying to filter by a boolean column on my Users table and I've tried making it a select box and check box, neither method works

```
filter :admin_created
filter :admin_created, collection: [["Yes", true], ["No", false]]
filter :admin_created, as: :select, collection: [["Yes", true], ["No", false]]
filter :admin_created, as: :check_boxes, collection: [["Yes", true], ["No", false]]
```

Neither of the above filter properly:

<img width="1251" alt="screen shot 2018-01-15 at 12 45 02 pm" src="https://user-images.githubusercontent.com/671929/34959595-cf82fbcc-f9fc-11e7-9799-6ed027cc0190.png">

**Comment by joshmn** [comment] 2018-01-20 20:34
Are you able to reproduce this on the demo app? https://github.com/activeadmin/demo.activeadmin.info

**Comment by zorab47** [comment] 2018-01-23 16:29
Is `admin_created` the name of the column? What SQL is generated in the Rails log when the filter is applied?

**Comment by 8vius** [comment] 2018-01-23 16:35
@zorab47 yeah admin created is the name of the column. @joshmn let me try and replicate in the demo.

**Comment by wspurgin** [comment] 2018-01-23 17:56
Is the column a `boolean` column? (i.e. what does `User.columns_hash[:admin_created].type` return?)

If you want to force the boolean filter rendering you have to add the `as: :boolean` option to the filter declaration.

**Comment by 8vius** [comment] 2018-01-31 17:15
@wspurgin yes the column is a boolean value.

**Comment by wspurgin** [comment] 2018-01-31 18:24
@8vius Have you also tried forcing the `boolean` representation?

```
filter :admin_created, as: :boolean
```

The default filter _should_ have produced the typical "Yes/No" drop down like the one for the [Feature filter on the Product](http://demo.activeadmin.info/admin/products) resource page of the demo. If forcing the `as: :boolean` still doesn't work, here are my next two questions:

1. What version of AA are you using?
2. Do you have an custom CSS or styling in your app (at all).

From what I can see in the photo you posted, it _looks_ like you're using an older version of AA (just based on the styling), but without knowing more information, I'm not sure we can help you much more than we have already.

**Comment by varyonic** [comment] 2018-09-28 15:31
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.

**Closed by varyonic** 2018-09-28 15:31 UTC

**Comment by ntloi95** [comment] 2019-12-22 11:12
> @8vius Have you also tried forcing the `boolean` representation?
> 
> ```
> filter :admin_created, as: :boolean
> ```
> 
> The default filter _should_ have produced the typical "Yes/No" drop down like the one for the [Feature filter on the Product](http://demo.activeadmin.info/admin/products) resource page of the demo. If forcing the `as: :boolean` still doesn't work, here are my next two questions:
> 
> 1. What version of AA are you using?
> 2. Do you have an custom CSS or styling in your app (at all).
> 
> From what I can see in the photo you posted, it _looks_ like you're using an older version of AA (just based on the styling), but without knowing more information, I'm not sure we can help you much more than we have already.
Force using as: :boolean is worked.
