### ISSUE TITLE
Contact model links all go to contact-us page

### ISSUE THREAD

**Issue by julieushpa** [activeadmin/activeadmin#4643] opened 2016-09-27 19:00 UTC
(I posted on [stackoverflow](http://stackoverflow.com/questions/39671906/activeadmin-details-for-contact-goes-to-page-with-similar-name), but haven't received any help there so I'm cross-posting here)
I realize that this issue is likely in my app code, but I'm stumped as to where to look at this point.

I've successfully installed ActiveAdmin 1.0.0.pre4 on rails 4.2.1 (following instructions [these instructions](http://www.activeadmin.org/docs/0-installation.html)). I turned off authentication, since we already have devise set up with a custom admin system and I will configure ActiveAdmin to use it once we know it's working for us. I also configured the default_namespace to be activeadmin (not admin) since we already have custom administration tools under /admin.

/activeadmin successfully shows the Dashboard. So I added two models (Contact and Flag). Flags (/activeadmin/flags) works as expected - it shows all the records and Id, View, and Edit all link to the appropriate details view.

For Contacts, the list view works as expected (/activeadmin/contacts). It shows the records and the filters seem to work.

The problem is if I click on the Id, View or Edit links for any Contact they all show the same content: the details view of one of my Page records (which I had not yet even configured for ActiveAdmin). They show the SAME Page details - it has the title "Contact Us" (and the slug "contact-us"). Everything in the ActiveAdmin UI looks as it should: the URL is /activeadmin/contacts/39, the breadcrumb is right, even the panel title says "Contact Details". But regardless of which contact I choose, it always shows the Contact Us page.

I can short-circuit it by editing the contact.rb file for ActiveAdmin. However, I can only get it to show the "title" (from the Page Contact Us), not any other field. Everything else (whether it's from the Page model or the Contact model) throws an exception: undefined local variable or method `body' for #ActiveAdmin::Views::Pages::Show:0x007fdfff3e7c40 Note that it's clearly looking for Pages, not Contacts. The request parameter is: {"controller"=>"activeadmin/contacts", "action"=>"show", "id"=>"39"}

Previously I had thought it had to do with the slug, although I have removed the friendly_id gem and commented out the code that references it (and errors imply it's no longer working). It made no difference.

Also: - /activeadmin/contacts/ all show the Contact Us page details - /activeadmin/contact-us or contact (with or without a /) gives a routing error (No route matches [GET] "/activeadmin/...")

I tried adding my Page model and then customizing page.rb with
ActiveAdmin.register Page, :as => "fancy_page"
(as I'd read in issue 959). But this did not change the behavior. Fancy Pages does indeed list all my pages, and Id, View, and Edit all link to the correct details page.

Rewriting my entire application to rename the Page model would be extremely difficult (the front-end website and associated custom CMS is the one part of our app that is fully working and live). I'm hoping there is a simpler fix, but I'm not really sure where to look.

Any suggestions?

Thanks!
julie

**Comment by timoschilling** [comment] 2016-09-28 08:08
please post your `routes.rb` file

**Comment by julieushpa** [comment] 2016-09-28 19:00
Here is my routes.rb file. Thanks for any insight you can provide!
```
require 'modules/legacy_routes'
require 'sidekiq/web'

Rails.application.routes.draw do
#TODO 911 i don't think we need devise yet since we don't have logins yet
#  devise_for :admin_users, ActiveAdmin::Devise.config
  use_doorkeeper
  # Redirects to handle existing URLs from the legacy site, so that
  # existing links and the like continue to work as expected. Note:
  # The existence of these redirects is not just for the "hybrid"
  # period, but some of the targets (with the /legacy URLs) will need
  # to be changed once that functionality is working in this
  # application.

  extend LegacyRoutes
  redirects


  get '/preflightsafety', to: redirect('/page/preflight-safety-apps-available')
  get '/filmfestival', to: redirect('/page/2015-ushpa-free-flight-film-festival')
  get '/sweepstakes', to: redirect('/page/ushpa-sweet-2015-sweepstakes')
  get '/freeflightforever', to: redirect('/page/free-flight-forever-campaign')
  get '/elections', to: redirect('/page/elections')
  get '/safety', to: redirect('/page/safety')
  get '/survey', to: redirect('/page/ushpa-instruction-evaluation')

  get '/page/search-instructors', to: redirect('/legacy/instructors_map-hybrid.asp')
  #get '/page/search-schools', to: redirect('http://www.pasaschools.org/certified-free-flight-schools/')

  get '/facebook', to: redirect('https://www.facebook.com/pages/United-States-Hang-Gliding-and-Paragliding-Assn-Inc-Ushpa/250881831591967')
  get '/store', to: redirect('http://ushpastore.com')
  get '/fftrailer', to: redirect('https://www.youtube.com/watch?v=uVoXZHk9dtg&feature=youtu.be')


  # --- V1 "hybrid" proxies ---

  # For the period of time when this application and the legacy web
  # site are both online, there are certain URLs that we respond to,
  # but we pull content from the legacy site.


  # Pages that will appear in the main web site, that pull from
  # ushpa.aero, and are included in fully formatted pages with menu
  # and the like.

  get '/legacy/*legacy_page', to: 'legacy_site#view_page', as: :legacy_site_view_page


  # Special pages for the QR codes that appear on membership cards. We
  # are passing through these requests with almost no changes, except
  # that we'll hack specific URLs to go back through us.

  ['m', 'M'].each do |passthrough_prefix|
    get "/#{passthrough_prefix}/*passthrough_path", to: 'legacy_site#direct_passthrough'
  end


  # The hacked URLs can come through here.
  get '/legacy_api/*legacy_api_page', to: 'legacy_site#api_passthrough'




  # --- End of V1 proxies ---


  # --- V2-specific entries ---

  # Uncomment these for V2, when we comment out the proxies above.

=begin

  get '/m/:id', to: 'members_area/memberships#mobile_qr'
  get '/M/:id', to: 'members_area/memberships#mobile_qr'

=end

  # --- End of V2-specific entries ---


  resources :pages, only: [:show, :index]
  root 'site#home'
  get 'site/no_access', to: 'site#no_access', as: :no_access

  resources :members_area, only: [:index]
  get 'members_area/sign_in' => 'members_area#sign_in', as: :members_sign_in

  namespace :members_area do
    resources :contacts, except: [:show]
    get 'contacts/profile' => 'contacts#profile', as: :profile
    get 'contacts/update' => 'contacts#update', as: :update
    get 'contacts/receipts/:id' => 'contacts#receipts', as: :receipts

    get 'contacts/search_results', to: 'contacts#search_results', as: :search_results
    resources :memberships
    get 'memberships/cards', to: 'memberships#cards', as: :card
    get 'memberships/show_pdf/:contact_id', to: 'memberships#show_pdf', as: :show_pdf
    get 'memberships/add' => 'memberships#add', as: :add_membership

    resources :news
    get '/page/:page_id' => 'site#page', as: :site_page
  end


  devise_for :users, path: 'auth', :controllers => {:confirmations => 'confirmations', :sessions => 'sessions', :passwords => 'passwords'}

  devise_scope :user do
    patch 'auth/confirm' => 'confirmations#confirm'
    get   'auth/info'    => 'sessions#info'
  end

# TODO 911 - i'm not sure this is correct, but seems like it might be needed
  namespace :active_admin do
    mount ActiveAdmin::Engine => '/activeadmin', as: 'activeadmin'
  end

  namespace :admin do
    mount RailsAdmin::Engine => '/deep', as: 'rails_admin'
    authenticate :user do
      mount Sidekiq::Web => '/sidekiq'
    end

    # resources :contacts, except: [:show]
    resources :pages

    get '/pages/add_page_link.js.erb', to: 'pages#add_page_link', as: :add_page_link
    post 'upload_image', to: 'pages#upload_image', as: :upload_image
    get 'disable_section_option', to: 'pages#disable_section_option'

    resources :pages do
      member do
        get 'mark_archived', to: 'pages#mark_archived', as: :mark_archived
        get 'mark_published', to: 'pages#mark_published', as: :mark_published
        get 'publish_today', to: 'pages#publish_today', as: :publish_today
        get 'pages/confirmation', to: 'pages#confirmation', as: :confirmation

      end
    end

    resources :homepages


    # resources :news, :controller => 'pages'
    # resources :evergreen, :controller => 'pages'
    resources :news_pages, :controller => 'pages'
    resources :evergreen_pages, :controller => 'pages'
    resources :list_pages, :controller => 'pages'
    resources :grid_list_pages, :controller => 'pages'
    resources :ratings do
      collection do
        match 'search' => 'ratings#search', via: [:get, :post], as: :search
      end
    end
    get '/ratings/new/:contact_id' => 'ratings#new'
    get '/ratings/assign/:shopping_cart_item_id/:contact_id' => 'ratings#assign', as: :assign_ratings

    resources :page_versions
    resources :page_versions do
      get 'page_versions/show/:id' => "page_versions#show"
      get 'mark_version_published/:id', to: 'page_versions#mark_version_published', as: :mark_published
    end

    resources :memberships
    get '/memberships/member_number/:id' => 'memberships#member_number', as: :member_number
    patch 'update_member_number' => 'memberships#update_member_number', as: :update_member_number
    get '/memberships/new/:contact_id' => 'memberships#new', as: :new_membership
    get '/memberships/legal/:id' => 'memberships#legal', as: :legal
    get '/memberships/waiver_missing/:id' => 'memberships#waiver_missing', as: :waiver_missing
    patch 'add_waiver/:id' => 'memberships#add_waiver', as: :add_waiver
    get '/memberships/needs_waiver/:id' => 'memberships#needs_waiver', as: :needs_waiver
    get '/memberships/card/:contact_id' => 'memberships#card', as: :membership_card
    get '/memberships/new/:contact_id' => 'memberships#new'
    get 'memberships/pdf_membership_card/:contact_id', to: 'memberships#pdf_membership_card', as: :pdf_membership_card

    # UA 2015-11-26: resources :contacts, like :link_lists, :links, :pages etc. is declared twice, which does not make sense
    resources :contacts, except: [:edit]
    get 'trigger_card', to: 'contacts#trigger_card', as: :trigger_card
    resources :contacts do
      member do
        #get 'contacts/search' => "contacts#search", as: :admin_contact_search
        get 'invite_user', to: 'contacts#invite_user', as: :invite_user
        # get 'flag_contact',  to: 'contacts#invite_user', as: :flag_contact  20151104 EW Consider Deleting

      end
      # collection do
      #   match 'search' => 'contacts#search', via: [:get, :post], as: :search
      # end
      resources :contact_notes, only: [:create]
    end
    resources :contact_notes, only: [:show, :update]

    resources :photos
    resources :ads
    get 'mark_active/:id', to: 'photos#mark_active', as: :mark_photo_active
    get 'mark_archived/:id', to: 'photos#mark_archived', as: :mark_photo_archived
    get 'mark_ad_active/:id', to: 'ads#mark_active', as: :mark_ad_active
    get 'mark_ad_archived/:id', to: 'ads#mark_archived', as: :mark_ad_archived
    get 'mark_homepage_active/:id', to: 'homepages#mark_active', as: :mark_homepage_active
    get 'mark_homepage_archived/:id', to: 'homepages#mark_archived', as: :mark_homepage_archived

    resources :gallery_img_media_items, :controller => 'photos'


    get 'contacts/step_two/:id', to: 'contacts#step_two', as: :contact_step_two
    get 'contacts/step_three/:id', to: 'contacts#step_three', as: :contact_step_three
    patch 'step_two_update', to: 'contacts#step_two_update', as: :contact_step_two_update
    get '/admin/contacts/add_flag' => 'contacts#add_flag', as: :add_flag
    post 'create_flag' => 'contacts#create_flag', as: :create_flag
    get '/admin/contacts/edit_flag' => 'contacts#edit_flag', as: :edit_flag
    patch 'update_flag' => 'contacts#update_flag', as: :update_flag
    get '/admin/contacts/edit_password' => 'contacts#edit_password', as: :edit_password
    patch 'update_password' => 'contacts#update_password', as: :update_password
    post 'contacts/reset_password' => 'contacts#reset_password', as: :reset_password

    resources :shopping_carts

    get '/shopping_carts/add_item/:product_id', to: 'shopping_carts#add_item', as: :add_item
    post 'add_rating_cart_item/:bundle_id' , to:'shopping_carts#add_rating_cart_item', as: :add_rating_cart_item
    post 'add_bundle_cart_item/:product_id' , to:'shopping_carts#add_bundle_cart_item', as: :add_bundle_cart_item
    post 'add_discount/:product_id' , to: 'shopping_carts#add_discount', as: :add_discount
    post 'add_membership_item/:product_id/:contact_id/:upgrade' , to: 'shopping_carts#add_membership_item', as: :add_membership_item
    get 'remove_item', to: 'shopping_carts#remove_item', as: :remove_cart_item
    get '/shopping_carts/checkout/:id', to: 'shopping_carts#checkout', as: :checkout

    resources :member_transactions
    get '/member_transactions/receipt/:id' => 'member_transactions#receipt', as: :receipt

    resources :link_lists
    resources :link_lists do
      member do
        get '/manage/' => 'link_lists#manage', as: :manage
        get '/navigation/edit' => 'link_lists#edit_navigation', as: :edit_navigation
      end
    end
    resources :links
    resources :links do
      member do
        get 'remove_external_link' => 'links#remove_external_link', as: :remove_external_link
      end
    end
    resources :link_list_groups
    resources :link_list_groups do
      collection { post :sort }
    end
    resources :page_links
    resources :page_links do
      member do
        get 'remove_page_link' => 'page_links#remove_page_link', as: :remove
      end
    end

    resources :topics do
      member do
        get 'remove_topic' => 'topics#remove_topic', as: :remove
      end
    end

    resources :schools do
      collection do
        match 'search' => 'schools#search', via: [:get, :post], as: :search
      end
    end
    resources :chapters
    resources :sites
    resources :membership_card_batches, only: [:index]
    get 'run_card_order_job/:start_datetime/:end_datetime', to: 'membership_card_batches#run_card_order_job', as: :run_card_order_job

    resources :email_logs, only: [:index]
    get 'run_email_job/:amount', to: 'email_logs#run_email_job', as: :run_email_job

    resources :postcard_batches, only: [:index]
    get 'mark_downloaded/:id', to: 'postcard_batches#mark_downloaded', as: :mark_postcard_downloaded
    get 'mark_ordered/:id', to: 'postcard_batches#mark_ordered', as: :mark_postcard_ordered
    get "home/download_postcard_csv"
    get 'run_postcard_job/:amount', to: 'postcard_batches#run_postcard_job', as: :run_postcard_job
    # get '/admin/topics/add'  =>  'topics#add', as: :add_topic
    # post 'create_topic_from_page'  => 'topics#create_topic_from_page', as: :create_topic
    get '/admin/topics/add_from_new' => 'topics#add_from_new', as: :add_from_new
    post 'create_topic_from_new' => 'topics#create_topic_from_new', as: :create_topic_from_new
    get '/admin/topics/add_from_edit' => 'topics#add_from_edit', as: :add_from_edit
    post 'create_topic_from_edit' => 'topics#create_topic_from_edit', as: :create_topic_from_edit
    get '/admin/topics/add_from_version' => 'topics#add_from_version', as: :add_from_version
    post 'create_topic_from_version' => 'topics#create_topic_from_version', as: :create_topic_from_version

    get '/admin/topics/edit_topic' => 'topics#edit_topic', as: :edit_topic
    patch '/admin/topics/update/:id' => 'topics#update', as: :update_topic
  end

  # Static routes for utility pages
  get '/test' => 'static#test', as: :test

  # Simple number-based routes to get site content
  get '/page/:page_id' => 'site#page', as: :site_page
  get '/bio/:role_id' => 'site#bio', as: :site_bio
  get '/home/:home_id' => 'site#home', as: :site_home
  get '/media/:media_item_id' => 'site#media', as: :site_media_item, constraints: {media_item_id: /\d+/}
  get '/news/:section_id' => 'site#news', as: :site_news
  get '/school/:school_id' => 'site#school', as: :site_school

  get '/topic/:topic_id' => 'site#topic', as: :site_topic
  get '/site/extras/more_info' => 'site#more_info', as: :more_info
  get 'instructor' => 'site#instructor', as: :instructor


  # request info form submission to legacy site
  post '/submit_lead', to: 'legacy_site#submit_lead'
  get '/request_info_thank_you_page', to:'site#request_info_thank_you_page'

  # site wide search routes
  match '/site-wide-search' => 'search#sitewide_search',  via: [:get, :post], as: :site_wide_search



  # We are getting a lot of error hits to //media/ushpa_logo_lg and similar URLs. Treat them as JPGs.

  get "//media/:legacy_bad_media_path", to: 'legacy_site#view_bad_media'


  namespace :api do
    namespace :v1 do
      resources :members
      resources :rating_types, only: [:index]
      #match ':resource/:id' => 'api#foo', via: [:get, :post]
    end
  end

  #admin login
  namespace :admin do
    get '/', to: 'pages#index'
  end

  # route to handle the excepitons or error
  match '/404', :to => 'errors#show', :via => :all
  match '/500', :to => 'errors#show', :via => :all

  # TODO 911 - moved this ActiveAdmin routes call to the very end as an experiment
  ActiveAdmin.routes(self)
end
```

**Comment by julieushpa** [comment] 2016-10-16 22:06
@timoschilling - I posted my routes.rb file. any thoughts? thanks!

**Comment by timoschilling** [comment] 2016-10-17 07:58
I think I have found the problem, please give me the `active_admin.rb` file and the result of `rake routes`

**Comment by julieushpa** [comment] 2016-10-17 23:56
Hi @timoschilling 
Attached are the files.
Thank you!
julie
[activeadmin_issue-julieushpa.zip](https://github.com/activeadmin/activeadmin/files/534931/activeadmin_issue-julieushpa.zip)

**Comment by julieushpa** [comment] 2016-11-03 18:10
Hi @timoschilling 
Attached are the files.
Thank you!
julie

**Comment by julieushpa** [comment] 2016-11-03 18:10
Hi again @timoschilling -
By any chance have you discovered anything?
Thanks!
julie

**Comment by timoschilling** [comment] 2016-11-03 21:34
For the next time: please do not post a zip file, that sucks, post the files as gist!

remove this:
```ruby
  namespace :active_admin do
    mount ActiveAdmin::Engine => '/activeadmin', as: 'activeadmin'
  end
```

and move this to the top of your routes.rb:
```ruby
ActiveAdmin.routes(self)
```

What happens?

**Comment by julieushpa** [comment] 2016-11-04 01:29
Sorry about the ZIP - I'm old-school and when it wouldn't let me upload the file directly....

I made the two changes you suggested. Everything appears to be working exactly the same as it was before making the changes. Including the "Contact Us" page details being shown instead of the Contact details for the selected Contact.

Any other ideas of what to try?

**Comment by timoschilling** [comment] 2016-11-04 01:33
You should keep `mount ActiveAdmin::Engine` way, it's not needed, `ActiveAdmin.routes(self)` is all you need.

**Comment by julieushpa** [comment] 2016-11-04 01:37
I'm sorry, I don't completely understand this last comment. 
> You should keep mount ActiveAdmin::Engine way, it's not needed

I commented out the namespace... code (including ```mount ActiveAdmin::Engine```) as you suggested 
AND I moved ```ActiveAdmin.routes(self)``` to the top.

One thing to note is that we have /admin routing to our custom administration UI. Although even with the changes you suggest I was still able to reach the active admin ui via /activeadmin.

**Comment by timoschilling** [comment] 2016-11-04 01:41
What I meen is, completely delete this code, it is bulshit:
```ruby
 namespace :active_admin do
    mount ActiveAdmin::Engine => '/activeadmin', as: 'activeadmin'
  end
```
ActiveAdmin has a Engine, but this Engine is not mountable, like the RailsAdmin::Engine.

**Comment by timoschilling** [comment] 2016-11-04 01:42
Can you provide screenshots from the wrong pages and the console output from the related request.

**Comment by julieushpa** [comment] 2016-11-04 02:37
Here is the console output from the 3 requests (plus the sort, so I could show a test user):
```
19:31:46 web.1    | [44282] 127.0.0.1 - - [03/Nov/2016:19:31:46 -0700] "GET /activeadmin HTTP/1.1" 200 - 0.2506
19:32:01 web.1    | [44282] 127.0.0.1 - - [03/Nov/2016:19:32:01 -0700] "GET /activeadmin/contacts HTTP/1.1" 200 - 1.0747
19:32:09 web.1    | [44282] 127.0.0.1 - - [03/Nov/2016:19:32:09 -0700] "GET /activeadmin/contacts?order=first_name_desc HTTP/1.1" 200 - 1.1546
19:32:34 web.1    | [44281] 127.0.0.1 - - [03/Nov/2016:19:32:34 -0700] "GET /activeadmin/contacts/32 HTTP/1.1" 200 - 0.2220
```

Here are the three screenshots of the resulting pages:
![1-activeadmin](https://cloud.githubusercontent.com/assets/13209684/19992628/c36a3c96-a1fc-11e6-8c5c-d17ad55bb0e6.png)
![2-activeadmin-contacts](https://cloud.githubusercontent.com/assets/13209684/19992630/c59cb78c-a1fc-11e6-8ad8-aaebf5a7694a.png)
![3-activeadmin-contacts-32](https://cloud.githubusercontent.com/assets/13209684/19992632/c7b0207c-a1fc-11e6-85be-06201fb6435e.png)

The contact ID I selected was #32, which is just coincidence that it's close to 33 (the page ID of contact-us). The contact-us page is shown regardless of which contact ID I select.

**Comment by julieushpa** [comment] 2016-11-09 19:49
Hi @timoschilling -
Any other thoughts?

My only other idea is to try renaming the Contact model to something else so see if it changes the behavior....
Thanks,
julie

**Comment by timoschilling** [comment] 2016-11-10 07:00
Please post the full rails console log, you post the foreman or something like that log.

**Comment by julieushpa** [comment] 2016-11-12 02:59
@timoschilling 
I'm not sure what you mean by "full rails console log". I'm running the site through foreman, so the output all goes to the shell and there is no logfile. Here is the entire output after initiating foreman start:
```
18:52:01 web.1         | started with pid 6108
18:52:01 redis.1       | started with pid 6109
18:52:01 worker.1      | started with pid 6110
18:52:01 mailcatcher.1 | started with pid 6111
18:52:01 redis.1       | 6109:C 11 Nov 18:52:01.749 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
18:52:01 redis.1       | 6109:M 11 Nov 18:52:01.751 * Increased maximum number of open files to 10032 (it was originally set to 256).
18:52:01 redis.1       |                 _._                                                  
18:52:01 redis.1       |            _.-``__ ''-._                                             
18:52:01 redis.1       |       _.-``    `.  `_.  ''-._           Redis 3.2.5 (00000000/0) 64 bit
18:52:01 redis.1       |   .-`` .-```.  ```\/    _.,_ ''-._                                   
18:52:01 redis.1       |  (    '      ,       .-`  | `,    )     Running in standalone mode
18:52:01 redis.1       |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
18:52:01 redis.1       |  |    `-._   `._    /     _.-'    |     PID: 6109
18:52:01 redis.1       |   `-._    `-._  `-./  _.-'    _.-'                                   
18:52:01 redis.1       |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
18:52:01 redis.1       |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
18:52:01 redis.1       |   `-._    `-._`-.__.-'_.-'    _.-'                                   
18:52:01 redis.1       |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
18:52:01 redis.1       |  |    `-._`-._        _.-'_.-'    |                                  
18:52:01 redis.1       |   `-._    `-._`-.__.-'_.-'    _.-'                                   
18:52:01 redis.1       |       `-._    `-.__.-'    _.-'                                       
18:52:01 redis.1       |           `-._        _.-'                                           
18:52:01 redis.1       |               `-.__.-'                                               
18:52:01 redis.1       | 
18:52:01 redis.1       | 6109:M 11 Nov 18:52:01.753 # Server started, Redis version 3.2.5
18:52:01 redis.1       | 6109:M 11 Nov 18:52:01.753 * DB loaded from disk: 0.000 seconds
18:52:01 redis.1       | 6109:M 11 Nov 18:52:01.753 * The server is now ready to accept connections on port 6379
18:52:02 web.1         | [6108] Puma starting in cluster mode...
18:52:02 web.1         | [6108] * Version 2.16.0 (ruby 2.2.2-p95), codename: Midwinter Nights Trance
18:52:02 web.1         | [6108] * Min threads: 5, max threads: 5
18:52:02 web.1         | [6108] * Environment: development
18:52:02 web.1         | [6108] * Process workers: 5
18:52:02 web.1         | [6108] * Preloading application
18:52:03 mailcatcher.1 | Starting MailCatcher
18:52:03 mailcatcher.1 | ==> smtp://127.0.0.1:1025
18:52:03 mailcatcher.1 | ==> http://127.0.0.1:1080
18:52:08 web.1         | v1.3.4-15-g74a0237
18:52:08 worker.1      | v1.3.4-15-g74a0237
18:52:08 web.1         | 2016-11-12T02:52:08.746Z 6108 TID-oxv3zrxmw DEBUG: Sidekiq client with redis options {:url=>"redis://localhost:6379/5", :namespace=>"harare"}
18:52:08 worker.1      | 2016-11-12T02:52:08.761Z 6110 TID-ovkd9uxh8 INFO: Booting Sidekiq 3.5.0 with redis options {:url=>"redis://localhost:6379/5", :namespace=>"harare"}
18:52:11 worker.1      | 2016-11-12T02:52:11.646Z 6110 TID-ovkd9uxh8 INFO: Running in ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
18:52:11 worker.1      | 2016-11-12T02:52:11.646Z 6110 TID-ovkd9uxh8 INFO: See LICENSE and the LGPL-3.0 for licensing details.
18:52:11 worker.1      | 2016-11-12T02:52:11.646Z 6110 TID-ovkd9uxh8 INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
18:52:11 worker.1      | 2016-11-12T02:52:11.647Z 6110 TID-ovkd9uxh8 DEBUG: Middleware: Sidekiq::Middleware::Server::Logging, Sidekiq::Failures::Middleware, Sidekiq::Middleware::Server::RetryJobs, Sidekiq::Middleware::Server::ActiveRecord
18:52:11 web.1         | [6108] * Listening on tcp://0.0.0.0:5000
18:52:11 web.1         | [6108] Use Ctrl-C to stop
18:52:11 worker.1      | 2016-11-12T02:52:11.662Z 6110 TID-ovkd9uxh8 INFO: Starting processing, hit Ctrl-C to stop
18:52:11 web.1         | [6108] - Worker 0 (pid: 6174) booted, phase: 0
18:52:11 web.1         | [6108] - Worker 1 (pid: 6175) booted, phase: 0
18:52:11 web.1         | [6108] - Worker 2 (pid: 6176) booted, phase: 0
18:52:11 web.1         | [6108] - Worker 3 (pid: 6177) booted, phase: 0
18:52:11 web.1         | [6108] - Worker 4 (pid: 6178) booted, phase: 0
18:52:11 worker.1      | 2016-11-12T02:52:11.726Z 6110 TID-ovkesv7jg DEBUG: {:queues=>["default", "legacy_migration"], :labels=>[], :concurrency=>25, :require=>".", :environment=>nil, :timeout=>8, :poll_interval_average=>nil, :average_scheduled_poll_interval=>15, :error_handlers=>[#<Sidekiq::ExceptionHandler::Logger:0x007fa83c2bb970>, #<Method: Airbrake::Sidekiq::ErrorHandler#notify_airbrake>, #<Proc:0x007fa83bdb7f28@/Users/julie/Desktop/Git Source/harare/config/initializers/sidekiq.rb:20>], :lifecycle_events=>{:startup=>[], :quiet=>[], :shutdown=>[]}, :dead_max_jobs=>10000, :dead_timeout_in_seconds=>15552000, "production"=>{:concurrency=>1, :queues=>["default", "legacy_migration"]}, :config_file=>"config/sidekiq.yml", :strict=>true, :tag=>"harare"}
18:52:26 web.1         | [6174] 127.0.0.1 - - [11/Nov/2016:18:52:26 -0800] "GET /activeadmin HTTP/1.1" 200 - 8.4858
18:52:26 web.1         | [6174] 127.0.0.1 - - [11/Nov/2016:18:52:26 -0800] "GET /active_admin-a4a8d1f22e8842d31ae9ef6d2fdb3b41b42dc29b524863c6e007565da0ea16b2.css HTTP/1.1" 200 113693 0.1136
18:52:26 web.1         | [6174] 127.0.0.1 - - [11/Nov/2016:18:52:26 -0800] "GET /active_admin/print-0d2e7f03764459ef660dc9c7d05fd70a8f3e5009ca86cea9ed553e57524a87d8.css HTTP/1.1" 200 22459 0.1863
18:52:33 web.1         | [6174] 127.0.0.1 - - [11/Nov/2016:18:52:33 -0800] "GET /activeadmin/contacts HTTP/1.1" 200 - 2.1816
18:52:43 web.1         | [6174] 127.0.0.1 - - [11/Nov/2016:18:52:43 -0800] "GET /activeadmin/contacts?order=id_asc HTTP/1.1" 200 - 1.2192
18:54:14 web.1         | [6178] 127.0.0.1 - - [11/Nov/2016:18:54:14 -0800] "GET /activeadmin/contacts?utf8=%E2%9C%93&q%5Bfirst_name_contains%5D=Timo&commit=Filter&order=id_asc HTTP/1.1" 200 - 2.7956
18:54:21 web.1         | [6178] 127.0.0.1 - - [11/Nov/2016:18:54:21 -0800] "GET /activeadmin/contacts/32 HTTP/1.1" 200 - 0.2987
```

I've asked 3 Rails developers and none of them know what you mean by "full rails console log". If this is not what you mean, can you be more specific about the information you would like to see?

Thanks!!
julie

P.S. The test user name "Timo" is actually a complete coincidence. I only just noticed it's also your name :-)

**Comment by Fivell** [comment] 2017-01-29 17:01
@julieushpa , did you resolve this?

**Comment by timoschilling** [comment] 2017-01-29 18:22
@julieushpa it should look like this:
```
Started GET "/" for 127.0.0.1 at 2017-01-27 19:17:46 +0100
Processing by WelcomeController#index as HTML
  Alchemy::Site Load (0.3ms)  SELECT "alchemy_sites".* FROM "alchemy_sites" LIMIT 1
  Alchemy::Language Load (0.3ms)  SELECT "alchemy_languages".* FROM "alchemy_languages" WHERE "alchemy_languages"."site_id" = 1 AND "alchemy_languages"."id" = 1 LIMIT 1
...
  Rendered layouts/_footer.html.haml (549.4ms)
  Rendered layouts/_conversion_tracking.html.haml (0.1ms)
Completed 200 OK in 1687.2ms (Views: 1659.0ms | ActiveRecord: 10.6ms)
```

**Comment by julieushpa** [comment] 2017-01-30 23:31
@timoschilling - I provided the output of my Rails console log. Apparently I am using a different log level than you are. Mine is set to ```:warn```.

Can you tell me what level you would like my logging set to and I can generate a new log?

Thanks!
julie

**Comment by timoschilling** [comment] 2017-01-31 08:47
@julieushpa your output isn't from a rails console, it is from foremen or what ever. I don't know what the default log level is. Maybe you can find the needed log data in `log/development.log`.

**Comment by julieushpa** [comment] 2017-01-31 19:33
Screenshots previously provided are still accurate for the sequence used to duplicate the issue. Here is the log/development.log file contents:
https://gist.github.com/julieushpa/5d1a9e04ca0287b29526fd2fe9bf1afa

Thanks for the tip about log/development.log - I'd never come across that before.
julie

**Comment by timoschilling** [comment] 2017-01-31 21:24
@julieushpa that looks better, I will take a deeper look later

**Comment by julieushpa** [comment] 2017-01-31 21:28
@timoschilling - great! thanks.

**Comment by julieushpa** [comment] 2017-02-09 17:07
I hope my accidental click on the "Close and comment" button didn't confuse anyone - I reopened immediately since I didn't know how to "undo" my mistake.

This problem is still open and I'd love to hear any insight anyone has. Thanks!

**Comment by Fivell** [comment] 2017-02-09 17:20
@julieushpa , why this happens https://gist.github.com/julieushpa/5d1a9e04ca0287b29526fd2fe9bf1afa#file-development-log-L114-L120 ? This is not ActiveAdmin related queries

**Comment by julieushpa** [comment] 2017-02-09 17:39
@Fivell -  I'm not sure what "this" you mean. that is exactly my log file from navigating to my ActiveAdmin page (/activeadmin in my case), and attempting to edit a Contact record (as was described in the screenshots posted Nov 3, 2016).

**Comment by Fivell** [comment] 2017-02-09 17:40
@julieushpa ,  many queries like 
```
 SELECT  "pages".* FROM "pages" WHERE "pages"."deleted_at" IS NULL AND "pages"."is_foundation" = 't' AND "pages"."slug" = $1  ORDER BY "pages"."id" ASC LIMIT 1  [["slug", "terms-conditions"]]

```

do you use friendlyid gem or something similar ?

**Comment by julieushpa** [comment] 2017-02-09 21:52
@Fivell - good point about all the selects. i see where they're coming from but not sure why they're in there (i'm looking into it). however, i'm not sure how loading those pages unnecessarily would result in the problem I'm seeing with editing a Contact record.

**Comment by deivid-rodriguez** [comment] 2017-04-23 13:37
@julieushpa Did you have time to investigate the select queries? Also, you have posted a lot of code here, I think you're close to being able to provide a reproducible application. That would be helpful for us since it would give us a way to see the error for ourselves.

I'm going to close this issue for now since you haven't provided any feedback for a long time, but feel free to just reopen if you want to keep digging and provide more information.

**Closed by deivid-rodriguez** 2017-04-23 13:37 UTC
Labels: bug?, Routing

**Comment by julieushpa** [comment] 2017-04-24 17:35
It is unclear how the select queries have anything to do with the error we are seeing. At this point we are looking at alternative products.

**Comment by deivid-rodriguez** [comment] 2017-04-24 17:50
Thanks for the feedback!

**Comment by mkalygin** [comment] 2019-05-06 22:37
@julieushpa @Fivell @timoschilling I know it's super old, but I've found that a possible reason here is that you set instance variable in you base controller, so that this method always returns the same record: https://github.com/activeadmin/inherited_resources/blob/master/lib/inherited_resources/base_helpers.rb#L216.
