### ISSUE TITLE
Errors with documented way of displaying form errors

### ISSUE THREAD

**Issue by amit** [activeadmin/activeadmin#7464] opened 2022-04-25 23:11 UTC
### Did you find a bug?

This is for activeadmin (2.12.0) and rails (7.0.2.3) with ruby 3.0.4

Since Rails 6.2, the code as recommended in [https://github.com/activeadmin/activeadmin/blob/master/docs/5-forms.md#displaying-errors] throws errors
### Expected behavior

It should display the errors in the form fields inline

### Actual behavior
Error because of ActiveModel::Errors changes since rails 6.2.  

What actually happens?
Error is thrown: `ActionView::Template::Error (undefined method 'keys' for #<ActiveModel::Errors []>`
This is thrown at the line :
` f.semantic_errors *f.object.errors.keys`
f.object is ActiveModel::Errors and since Rails 6.2, it does not have the keys method any more!

## Fix

The documentation should be fixed (https://github.com/activeadmin/activeadmin/blob/master/docs/5-forms.md#displaying-errors)

at the minimum just use the following code:
`f.semantic_errors`

**Comment by deivid-rodriguez** [comment] 2022-04-27 18:24
@amit Thank you for letting us know! Can you provide a fix for this?

**Comment by Antonio-ArceG** [comment] 2022-04-28 02:10
I've recently had to fix this at work. The problem seems to be caused by Rails new way of handling errors. Before rails 6.1, errors were returned in a hash-like interface. After Rails 6.1, errors are now returned as an array of object, hence why `f.object.errors.keys` would not work if you rails version is above.

The correct  way to get error keys is now through method `:attribute_names`

meaning `f.semantic_errors *f.object.errors.keys` should now be `f.semantic_errors *f.object.errors.attribute_names`

Or at least that's my work-around

**Comment by deivid-rodriguez** [comment] 2022-04-28 06:43
Awesome, does that work in all supported Rails versions?

**Comment by Antonio-ArceG** [comment] 2022-05-02 01:14
Not 100% sure. I think my suggestion should only work for rails 6.1 and above since that's when the changes to errors came in place. For anything before 6.1  you could use the old way `f.semantic_errors *f.object.errors.keys`.

Have a read of the rails 6.1. release notes for more:

https://guides.rubyonrails.org/6_1_release_notes.html

**Comment by deivid-rodriguez** [comment] 2022-05-02 15:32
Right. I think we can go ahead and drop Rails 6.0 support, and update documentation to use the new way.

**Comment by amit** [comment] 2022-05-03 14:54
> @amit Thank you for letting us know! Can you provide a fix for this?

Here is the Pull request for review:
https://github.com/activeadmin/activeadmin/pull/7475

**Closed** 2022-05-03 21:56 UTC

**Comment by thenano** [comment] 2022-10-27 01:10
Hi all,

Thanks so much for fixing this and maintaining this library overall!
Any ideas when this fix will get a release?
