### ISSUE TITLE
[Rails 5] enctype: 'multipart/form-data' not added automatically ?

### ISSUE THREAD

**Issue by anthony-robin** [activeadmin/activeadmin#4669] opened 2016-11-22 20:19 UTC
Since I migrated my `Rails 4.2.7.1` app to `5.0.0.1`, I discovered that ActiveAdmin doesn't add anymore `enctype: 'multipart/form-data'` to the form view when a paperclip attribute is defined.

Is it a bug or the way to do it changed with Rails 5 ?

My project:
- Rails 5.0.0.1
- ActiveAdmin 1.0.0.pre4
- [Complete Gemfile](https://github.com/lr-agenceweb/rails-starter/blob/feature/Rails5/Gemfile.lock)

**Comment by varyonic** [comment] 2016-11-23 13:23
Might be related to #3732

**Comment by anthony-robin** [comment] 2016-11-24 17:45
Okay but this was merged almost 2 years ago. How to fix this issue ?

**Comment by varyonic** [comment] 2016-11-25 14:13
Set some breakpoints on lines of interest and compare what you see between Rails 4 and 5...

**Comment by varyonic** [comment] 2016-11-25 14:38
The relevant spec is https://github.com/activeadmin/activeadmin/blob/master/spec/unit/form_builder_spec.rb#L126  The original issue was #3577 which had quite a few participants.

**Comment by Fivell** [comment] 2017-01-20 10:16
@varyonic , how it can be ?  we have 5.0.1 rails in travis and we have spec 
https://github.com/activeadmin/activeadmin/blob/793ce0744712fcc1692d68481ad26e207cbd7c08/spec/unit/form_builder_spec.rb#L138

**Comment by varyonic** [comment] 2017-01-20 15:01
@anthony-robin Did the workaround in #3577 fix for you?  No-one else has reported a similar issue with 5.0 yet and we are unaware of any change that might have caused this.

**Comment by anthony-robin** [comment] 2017-01-20 15:48
@varyonic Yes, with the workaround explained in #3577, I am able to upload files with paperclip but without it I still get an `No handler found for "my_picture.png"` error.

I tried to update my activeadmin version and even when tracking master (commit b1f96a39c612) the problem is still present.

**Comment by Fivell** [comment] 2017-01-24 14:07
@anthony-robin, you could update paperclip while updating rails , maybe there is root of problem

**Comment by deivid-rodriguez** [comment] 2017-04-22 20:16
@anthony-robin I'm going to close this since we haven't received feedback from you in a while.

Try upgrading paperclip like @Fivell suggested and also feel free to reopen with reproduction steps and it still doesn't work (ideally using our [bug report template](https://github.com/activeadmin/activeadmin/blob/master/lib/bug_report_templates/rails_5_master.rb)).

**Closed by deivid-rodriguez** 2017-04-22 20:16 UTC
Labels: workaround
