### ISSUE TITLE
CSV Export maintains last filtered state

### ISSUE THREAD

**Issue by stevepaulo** [activeadmin/activeadmin#4611] opened 2016-09-02 19:39 UTC
If I filter the index page for a data model, the CSV Export link at the bottom appropriately exports only those records that match the filter. If I change the filter, then the Export link appropriately handles that, too.

But if I click "Clear Filters," the CSV Export link actually exports whatever records match the previous filter. Refreshing the page doesn't help, and I've looked for some kind of caching going on that could be the culprit, without success.

Am I missing something? Or is this a real bug?

**Comment by prasadsurase** [comment] 2016-09-07 06:34
@stevepaulo I wasn't able to reproduce the error. I am using ruby(2.2.2), rails(4.2.5.2) and activeadmin(1.0.0.pre2). Could you please post a sample repo demonstrating the said error?

**Comment by stevepaulo** [comment] 2016-09-07 15:40
Unfortunately I can't produce a repo as this is occurring in an internal tool. I have slightly different versions, but nothing major (ruby 2.2.1, rails 4.2.0, AA 1.0.0.pre)

**Comment by timoschilling** [comment] 2016-09-28 08:19
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.

**Closed by timoschilling** 2016-09-28 08:19 UTC

**Comment by neilabdev** [comment] 2017-11-16 20:20
In my case, I was using a manually integrated module to save ActiveAdmin filters when pages are changed... This way, when you click back to the model's page with filters, it would contain prior search data. Code was added to clear filters to erase the saved filters in the session, but was not working for CSV's because the regular model's index :key used in the session was slightly different ActiveAdmin's CSV link, because it included the :format, which prevented that key from ever being deleted. The link to the code is here:

https://gist.github.com/tinynumbers/5896537

The troublesome line was here:

```ruby
def controller_key
        #params[:controller].gsub(/\//, '_').to_sym
        current_path = request.env['PATH_INFO']
        current_route = Rails.application.routes.recognize_path(current_path)
        current_route.sort.flatten.join('-').gsub(/\//, '_').to_sym # original line, BAD :( - produces :controller_model_index_csv
       "#{current_route[:controller]}/#{current_route[:action]}".gsub(/\//, '_').to_sym # produces :controller_model_index
      end
```

After applying the fix, it worked for me. Not an ActiveAdmin issue, but added here to help those that follow. Thx!
