### ISSUE TITLE
Nested Belongs_to does not work as expected

### ISSUE THREAD

**Issue by bamorim** [activeadmin/activeadmin#3274] opened 2014-07-12 22:29 UTC
It would be nice if active_admin support InheritedResources nested belongs_to

I'm putting it here but I'll try to implement that feature.

My suggestion is that ```belongs_to``` method instead of setting ```@belongs_to``` it would push a configuration to an array.

Then, the router could run through the belongs_tos setting the routes.

**Comment by seanlinsley** [comment] 2015-11-23 04:01
Closing as a duplicate of #2082

**Closed by seanlinsley** 2015-11-23 04:01 UTC
