### ISSUE TITLE
Formtastic to create deep nested form with active admin

### ISSUE THREAD

**Issue by cristianogregnanin** [activeadmin/activeadmin#6634] opened 2020-12-22 10:22 UTC
Using Rails 6, I am designing an application for manage police fines. 
A user can violate many articles, an article can have many letters and a letter can have many commas.

This is my implementations: 

```
#models/fine.rb
class Fine < ApplicationRecord
  has_many :violations
  has_many :articles, through: :violations
  has_many :letters, through: :violations
  has_many :commas, through: :violations
end
```

```
#models/article.rb
class Article < ApplicationRecord
  has_many :letters
  has_many :violations
  has_many :fines, through: :violations
end
```

```
#models/letter.rb
class Letter < ApplicationRecord
  belongs_to :article
  has_many :commas

  has_many :violations
  has_many :fines, through: :violations

end
```

```
#models/comma.rb
class Comma < ApplicationRecord
  belongs_to :letter

  has_many :violations
  has_many :fines, through: :violations
end
```

```
#models/violation.rb
class Violation < ApplicationRecord
  belongs_to :fine

  belongs_to :article
  belongs_to :letter, optional: true
  belongs_to :comma, optional: true
end
```

When I print the Fine in pdf I need to show violations: articles, letters and commas.

I have some difficult creating form to compile the Fine with articles,letters,commas becouse is too deep.

I am using Active Admin, when I create new Fine I want to associate many violations.

Violation example: 

```
Violation.new
 => #<Violation id: nil, article_id: nil, fine_id: nil, letter_id: nil, comma_id: nil, note: nil, created_at: nil, updated_at: nil> 
```

How can I create a form (using Active Admin, who use Formtastic) to associate many violations to a Fine?

Example form: when create new Fine I want associate articles, letters and commas:

[![enter image description here][1]][1]

Example (with sample data): 

```
Violation.new fine: fine, article: a, letter: a.letters.last, comma: a.letters.second.commas.last
 => #<Violation id: nil, article_id: 124, fine_id: 66, letter_id: 10, comma_id: 4, note: nil, created_at: nil, updated_at: nil> 
```

  [1]: https://i.stack.imgur.com/9eaFN.jpg

**Comment by deivid-rodriguez** [comment] 2020-12-23 11:06
Closing as a duplicate of https://github.com/formtastic/formtastic/issues/1319.

**Closed by deivid-rodriguez** 2020-12-23 11:06 UTC
