### ISSUE TITLE
Exporting CSV runs out of memory.

### ISSUE THREAD

**Issue by MatUrbanski** [activeadmin/activeadmin#4118] opened 2015-09-10 06:26 UTC
In my app when I export csv with around 100 thousand records heroku get out of memory. I noticed that when In my rails app I add to application.rb following line:

``` ruby
config.middleware.delete "ActiveRecord::QueryCache"
```

csv export takes much less ram than before and everything works fine. Is there any way to monkey patch csv export in active admin to work with disabled `ActiveRecord::QueryCache`?

**Comment by adamdunkley** [comment] 2015-10-07 16:05
@MatUrbanski We have the same problem here and I have verified your fix. What we find strange is that we don't use memory for our storage of query cache (we use `:mem_cache_store`). I also noted that when it is over the memory is not returned to the system so I think there is some sort of memory leak in `ActiveRecord::QueryCache` somewhere … perhaps it's something to do with how activeadmin paginates the orders or builds the CSV line? I ran a manual `GC.start` afterward and it cleared up the errant memory. 

I am going to try looking at the heap using https://github.com/Vasfed/heap_dump to see if I can figure out where the memory is being allocated from.

**Comment by MatUrbanski** [comment] 2015-10-07 16:13
I've fix that with overriding active_admin ```ActiveAdmin::CSVBuilder```
```
ActiveAdmin::CSVBuilder.class_eval do
  def build(controller, receiver)
    @collection = controller.send(:find_collection, except: :pagination)
    options = ActiveAdmin.application.csv_options.merge self.options
    columns = exec_columns controller.view_context

    if byte_order_mark = options.delete(:byte_order_mark)
      receiver << byte_order_mark
    end

    if options.delete(:column_names) { true }
      receiver << CSV.generate_line(columns.map{ |c| encode c.name, options }, options)
    end

    ActiveRecord::Base.uncached do
      @collection.find_each do |resource|
        resource = controller.send :apply_decorator, resource
        receiver << CSV.generate_line(build_row(resource, columns, options), options)
      end
    end
  end
end
```

**Comment by seanlinsley** [comment] 2015-10-11 02:45
@MatUrbanski interesting! I've never come across `uncached`, and it looks like exactly what we need.

**Comment by yhourdel** [comment] 2015-10-13 10:35
@MatUrbanski great fix, I've tested it inside our app in production and it works very well.
@seanlinsley I've forked the repo to be able to include this fix: should I make a pull request ?

**Comment by joallard** [comment] 2015-11-11 20:26
Whenever I try to download the CSV, I just get a 283-byte header with no records. I applied this patch in an initializer, no avail. CSV exporting in AA is my personal hell.

**Comment by seanlinsley** [comment] 2015-11-22 18:53
@joallard can you try reproducing in development with your production data? In particular since #3535 has been merged.

**Comment by seanlinsley** [comment] 2015-11-22 23:05
Perhaps part of the problem is that we're currently using Kaminari for CSV pagination where we used to use `find_each`. I've change that in #4209 if anyone would like to give it a try.

**Comment by MatUrbanski** [comment] 2015-11-30 07:48
Also I notice that ```ActiveAdmin::CSVBuilder``` class has hardcoded batch_size value. For now it is 1000, when I changed it to 100 my csv exports takes much less RAM...

**Comment by fredngo** [comment] 2017-05-10 14:44
This issue is already 1.5 years old but certainly still present... I know it's not good manners to "bump" issues but I gotta do it. :)

**Comment by yhourdel** [comment] 2017-05-11 22:25
@fredngo which version of Rails are you using?

**Comment by fredngo** [comment] 2017-05-12 15:36
@yhourdel Currently Rails is at 4.2.8 and ActiveAdmin is at the latest 1.0.0

**Comment by concept47** [comment] 2017-06-01 00:58
Having the same problem, just want to get notified if theres a fix. Rails 4.2.2. Active Admin 1.0.0

**Comment by fredngo** [comment] 2017-10-23 14:36
Since there is a "help wanted" label on this bug, I thought I'd lend a hand and submit this PR: https://github.com/activeadmin/activeadmin/pull/5218

**Closed** 2017-12-15 20:13 UTC
Labels: help wanted, workaround
