### ISSUE TITLE
Pagination links are not working 

### ISSUE THREAD

**Issue by martinbcg** [activeadmin/activeadmin#4459] opened 2016-06-03 21:35 UTC
Posted also on [Stackoverflow](http://stackoverflow.com/questions/37596643/activeadmin-pagination-not-working-with-ruby-2-3-1), where I couldn't found much help..

The problem is that all the links generated by ActiveAdmin's pagination are not working. For some reason they contain that strange piece of code (or error) than then I decoded manually for readability.

It is happening with all my models, so I think it have to be related with ActiveAdmin or Kaminari.

This is the link generated by the pagination (i.e. page 2): 

    http://localhost:5004/admin/end_customers?%23%3CProc%3A0x007fed48a49d80%40%2FUsers%2Fmartin%2F.rvm%2Fgems%2Fruby-2.3.1%2Fgems%2Ffacets-3.1.0%2Flib%2Fcore%2Ffacets%2Fsymbol%2Fcall.rb%3A24%3E=2&%23%3CProc%3A0x007fed494c6ba0%40%2FUsers%2Fmartin%2F.rvm%2Fgems%2Fruby-2.3.1%2Fgems%2Ffacets-3.1.0%2Flib%2Fcore%2Ffacets%2Fsymbol%2Fcall.rb%3A24%3E=2&order=id_desc

Decoded part of the URL ;) (for readability):

    <Proc:0x007feb2adc4d90@/Users/martin/.rvm/gems/ruby-2.3.1/gems/facets-3.1.0/lib/core/facets/symbol/call.rb:24>=2&#<Proc:0x007feb35418638@/Users/martin/.rvm/gems/ruby-2.3.1/gems/facets-3.1.0/lib/core/facets/symbol/call.rb:24>=2&order=id_desc

I am using Ruby 2.3.1. Rails 4.2.1, and ActiveAdmin 1.0.0.pre2

Thanks for your help.

**Comment by timoschilling** [comment] 2016-06-03 22:22
You use the `facets` gem, which monkey patches the `Symbol` class and that caused this error.

I close this issue, while the problem is not active admin related.

**Closed by timoschilling** 2016-06-03 22:22 UTC

**Comment by martinbcg** [comment] 2016-06-04 20:47
@timoschilling ok thanks. Any idea how I could fix it? Or that means just that facets gem would be incompatible?

**Comment by timoschilling** [comment] 2016-06-04 20:56
You should not use gems like facets which monkey patches Base Classes.

I don't know what do you need from facets, maybe it could help to require only the needed parts.
```
gem "facets", require: false
require 'facets/<class|module>/<method>'
```

**Comment by martinbcg** [comment] 2016-06-04 21:04
Ok thanks for your comment @timoschilling !
