### ISSUE TITLE
Custom labels not showing for check boxes on Safari.

### ISSUE THREAD

**Issue by jayahirsch** [activeadmin/activeadmin#7575] opened 2022-06-30 01:20 UTC
I'm having a bug that is essentially the same as this:

https://github.com/activeadmin/activeadmin/issues/5969

which seemed to be fixed in this commit:

https://github.com/fosterful/scheduler/commit/48a15955d6671d8c3a322dbc8f29c651ea8e01dc

But maybe that was lost in a later change.

**Comment by javierjulio** [comment] 2022-07-01 22:58
Duplicate of #5969

**Closed** 2022-07-01 22:58 UTC
