### ISSUE TITLE
default delete button is not working

### ISSUE THREAD

**Issue by sarbadaj** [activeadmin/activeadmin#4896] opened 2017-04-05 01:04 UTC
default delete button of user is not working

**Comment by troystarwalt** [comment] 2017-04-05 01:59
Can you share any of your code?

**Comment by brunto** [comment] 2017-04-14 09:58
Same error for me. When I click "Delete" on "Index" or "Show" page nothing is happening. No code to share because this issue is on all my models and on all "app/admin/*.rb" activeadmin register models.

**Comment by Fivell** [comment] 2017-04-14 10:08
@brunto, @sarbadaj , I can't reproduce, here is log for request with AA from master
```
Started DELETE "/admin/categories/1" for 127.0.0.1 at 2017-04-14 13:08:37 +0300
Processing by Admin::CategoriesController#destroy as HTML
  Parameters: {"authenticity_token"=>"AyCQ7kZFwlYxaCGdiEcwvto5V0ul6U8Uoa4Kqi2hMSs8wHp4wWn+JkCEuX6OHEyjhFP7TsAzz5evwADBqfAFtg==", "id"=>"1"}
  Category Load (0.2ms)  SELECT  "categories".* FROM "categories" WHERE "categories"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
   (0.1ms)  begin transaction
  SQL (0.4ms)  DELETE FROM "categories" WHERE "categories"."id" = ?  [["id", 1]]
   (0.6ms)  commit transaction
Redirected to http://127.0.0.1:3000/admin/categories
Completed 302 Found in 26ms (ActiveRecord: 1.3ms)
```

**Comment by brunto** [comment] 2017-04-14 10:11
Ok I understand instead of a DELETE I have a GET method.

`Started GET "/admin/users/33" for ::1 at 2017-04-14 12:09:42 +0200`

**Comment by brunto** [comment] 2017-04-14 10:14
Ok fixed for me, I had overwritten the file active_admin.js

**Comment by varyonic** [comment] 2017-04-22 15:29
@sarbadaj any update?

**Comment by Fivell** [comment] 2017-06-07 20:55
I’m going to close this since you haven’t responded. Please feel free to leave a comment requesting this issue be reopened if needed.

**Closed by Fivell** 2017-06-07 20:55 UTC
Labels: awaiting developer feedback

**Comment by saphirstone** [comment] 2018-09-25 14:29
hi guys! I have the same problem now! @brunto has solved the bug so can you tell me what did you paste on active_admin.js when you overwritten it? thanks
