### ISSUE TITLE
Edit of belong_to associations with larger datasets

### ISSUE THREAD

**Issue by andreasklinger** [activeadmin/activeadmin#3233] opened 2014-06-27 09:18 UTC
Hi all

First off: awesome work with activeadmin. I am highly impressed how much the project improved since the last time i used it a few years ago.

Question:
We have a model  that has a `belongs_to` relation with `User`

In `#index` i can do something awesome like:
`filter :user_username, as: :string` 

This works splendid

But in `#edit` i kinda ran against a wall. 
I need to be able to make it editable which user the model belongs to.

I can do something like

`f.input user` 

But this will load all XXX.000 user records as displays them as a `<select>`

I tried to integrate `select2` with typeahead but this turned out to be more complicated than anticipated because i basically need to add a dummy text_field to the form buffer and then tell select2 to update the real `user_id` which is hidden. But when i have errors the errors get hidden too… well that's also solveable somehow but then when i use `#edit` i would like to prefill that field so i need to do a starting ajax request… etc etc

all by itself somehow patch-able problems but together they feel like i am running the wrong way.

Is there a better recommended way to make an association that's not preloaded? If possible with autocomplete fields?
I am surely not the only user of active_admin that has more users than should be shown in a `<select>`. 

Thanks in advance

**Comment by bobzhen** [comment] 2015-10-08 06:02
thanks for mentioning 
```ruby
f.input user, as: :string
```
great help
@timoschilling

**Comment by seanlinsley** [comment] 2015-10-27 02:08
This is a duplicate of #2692

**Closed by seanlinsley** 2015-10-27 02:08 UTC
