### ISSUE TITLE
ActiveAdmin filter in simple setup leads to Ransack-Search crash

### ISSUE THREAD

**Issue by besi** [activeadmin/activeadmin#4326] opened 2016-02-22 09:39 UTC
I have a simple setup with only one model which I want to manage in ActiveAdmin. I do have approx 9800 entries in the DB.

When I deploy this to heroku then I get an error (See whole stacktrace below).

>     undefined method `catalog_nr_contains' for #<Ransack::Search:0x007fd29d3681f8>

I then explicitly included all the filters except `catalog_nr` and then I just get the next error similar to the initial one:

>    ActionView::Template::Error (undefined method `created_at_gteq' for #<Ransack::Search:0x007facd42daf68>):

### ActiveAdmin Resource:

```ruby
ActiveAdmin.register ImportObject do
  permit_params :catalog_nr, :collection, :address
end
```

## Model
```ruby
class ImportObject < ActiveRecord::Base
end
```

## Schema

```ruby

  create_table "import_objects", force: :cascade do |t|
    t.string   "catalog_nr",       limit: 255
    t.string   "collection",       limit: 255
    t.datetime "created_at",                     null: false
    t.datetime "updated_at",                     null: false
    t.string   "address",          limit: 255
    t.string   "city",             limit: 255
    t.string   "name_de",          limit: 255
    t.string   "collected_at",     limit: 255
    t.string   "year",             limit: 255
    t.string   "donor",            limit: 255
    t.string   "species_fr",       limit: 255
    t.string   "species",          limit: 255
    t.string   "quantity",         limit: 255
    t.string   "order",            limit: 255
    t.string   "first_name",       limit: 255
    t.string   "origin",           limit: 255
    t.text     "remarks",          limit: 65535
    t.string   "sex",              limit: 255
    t.string   "systematics",      limit: 255
    t.string   "age",              limit: 255
    t.string   "condition",        limit: 255
    t.string   "storage_location", limit: 255
    t.string   "group",            limit: 255
  end

```

## excerpt from Gemfile

```yaml
GEM
  remote: https://rubygems.org/
  specs:
    # ...
    ransack (1.7.0)
      actionpack (>= 3.0)
      activerecord (>= 3.0)
      activesupport (>= 3.0)
      i18n
      polyamorous (~> 1.2)
    # ...    
    activeadmin (1.0.0.pre2)
      arbre (~> 1.0, >= 1.0.2)
      bourbon
      coffee-rails
      formtastic (~> 3.1)
      formtastic_i18n
      inherited_resources (~> 1.6)
      jquery-rails
      jquery-ui-rails
      kaminari (~> 0.15)
      rails (>= 3.2, < 5.0)
      ransack (~> 1.3)
      sass-rails
    # ...    
    formtastic (3.1.3)
      actionpack (>= 3.2.13)
```

Internal reference `#8`

**Comment by besi** [comment] 2016-02-22 09:39
This might be related to #2565.

**Comment by besi** [comment] 2016-02-22 09:49
To have a working setup I just removed all the filters and deployed my app again. Now I realised that three fields on my Entity seem to be causing the problems, because for some reason active admin seems to refuse to sort those three columns:

![non-sorting-fields](https://cloud.githubusercontent.com/assets/160412/13214722/a1ae1fe2-d951-11e5-9a3f-7097dc6fa40e.png)

So now I can at least include those filters who don't conflict with Ransack:

```ruby
  #filter :catalog_nr
  filter :collection
  #filter :created_at
  #filter :updated_at
  filter :address
  filter :city
  filter :name_de
  filter :collected_at
  filter :year
  filter :donor
  filter :species_fr
  filter :species
  filter :quantity
  filter :order
  filter :first_name
  filter :origin
  filter :remarks
  filter :sex
  filter :systematics
  filter :age
  filter :condition
  filter :storage_location
  filter :group
```

Now the question is why I can't filter by `catalog_nr` as well as the two Rails-default dates `created_at` and `updated_at`.

**Comment by timoschilling** [comment] 2016-08-11 09:09
I can't reproduce your problem, can you provide a test app for that issue?

**Comment by timoschilling** [comment] 2016-08-24 23:42
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.

**Closed by timoschilling** 2016-08-24 23:42 UTC
