### ISSUE TITLE
Wrong date format in .pre4

### ISSUE THREAD

**Issue by abarriga** [activeadmin/activeadmin#4853] opened 2017-03-10 18:12 UTC
Using config.localize_format = :long

it's printing stuff like that:

m 09, 2016 10:23
t 08, 2016 14:08

**Comment by varyonic** [comment] 2017-03-31 14:49
Can you take a look at [the spec](https://github.com/activeadmin/activeadmin/blob/master/spec/unit/pretty_format_spec.rb) and let us know if we are missing something?  Steps to reproduce would be great.

**Comment by abarriga** [comment] 2017-04-04 13:31
I think this is not a good test for long format:

 it "should return a localized Date or Time with long format" do
      t = Time.now
      expect(self).to receive(:localize).with(t, {format: :long}) { "Just Now!" }
      expect(pretty_format(t)).to eq "Just Now!"
    end

Have you tested it with a real DateTime?

**Comment by deivid-rodriguez** [comment] 2017-04-22 20:03
@abarriga I had a quick look at this and I think it's very unlikely that this is a bug in AA since it does not provide any localization formats and it just relies on whatever your app uses.

I recommend you review your related translation keys (`time.formats.long` and `date.formats.long`).

Closing. Of course, feel free to reopen if you can provide us with a way of reproducing the issue.

**Closed by deivid-rodriguez** 2017-04-22 20:03 UTC

**Comment by varyonic** [comment] 2017-04-22 21:27
I do agree that the test is weak, which is why I did not close earlier.

**Comment by deivid-rodriguez** [comment] 2017-04-22 23:04
Yes, our code base is full of that kind of tests. I can write a better test for this, but the `:long` format seems fine to me.
