### ISSUE TITLE
Pagination looks broken

### ISSUE THREAD

**Issue by chrisjeon** [activeadmin/activeadmin#4173] opened 2015-10-27 02:44 UTC
Pagination looks broken. Is this type of pagination styling intentional?

<img width="1280" alt="screen shot 2015-10-26 at 9 43 03 pm" src="https://cloud.githubusercontent.com/assets/2433941/10748102/ae0868f8-7c2a-11e5-945b-bada48cbc78b.png">

**Comment by timoschilling** [comment] 2015-11-03 08:32
Pleas post the `<head>` tag and his content of that page

**Comment by seanlinsley** [comment] 2015-11-23 00:48
Closing due to a lack of details.

**Comment by mishatatinets** [comment] 2016-01-02 22:34
Same issue

**Comment by chrisjeon** [comment] 2016-01-02 22:55
Got a screenshot @mishatatinets ?

**Comment by mishatatinets** [comment] 2016-01-02 23:00
![screen shot 2016-01-02 at 3 59 16 pm](https://cloud.githubusercontent.com/assets/931951/12076493/e730ead2-b169-11e5-9a9b-575c4237c0b3.png)

**Comment by mishatatinets** [comment] 2016-01-02 23:05
Here is my head tag.
![screen shot 2016-01-02 at 4 04 43 pm](https://cloud.githubusercontent.com/assets/931951/12076510/a025b068-b16a-11e5-91cb-3c0f07a3ad4e.png)

**Comment by seanlinsley** [comment] 2016-01-02 23:07
What browser is that? Are you able to reproduce in other browsers?

Can you upload a test Rails app that we can run, that reproduces this issue?

**Comment by chrisjeon** [comment] 2016-01-02 23:13
Yeah, that's how mine looked like too. @seanlinsley I was using Chrome.

**Comment by mishatatinets** [comment] 2016-01-02 23:17
Both Safari and Chrome displays same things.
In pagination div I have a class  "pagination pagination-centered" 


![screen shot 2016-01-02 at 4 09 53 pm](https://cloud.githubusercontent.com/assets/931951/12076532/dc74a7e4-b16b-11e5-83b1-bb37620c78aa.png)

**Comment by mishatatinets** [comment] 2016-01-02 23:37
I also have kaminari folder in my view that renders this 

![screen shot 2016-01-02 at 4 33 17 pm](https://cloud.githubusercontent.com/assets/931951/12076584/e29a87ee-b16e-11e5-8909-5da0f27671d7.png)
![screen shot 2016-01-02 at 4 33 27 pm](https://cloud.githubusercontent.com/assets/931951/12076583/e299569e-b16e-11e5-823c-6887c923ca48.png)
 

I have to use it for other content  pagination.
Can this cost an issue?

**Comment by seanlinsley** [comment] 2016-01-02 23:46
@mishatatinets yes, that's what is causing this issue.

Historically we had our own Kaminari templates, but @timoschilling's #3653 removed those, so right now if you customize the Kaminari templates, Active Admin uses your version.

https://github.com/amatsuda/kaminari/pull/668 is a PR that could prevent this, but it has not been merged into Kaminari.

There was some discussion on #3840, which was proposed to revert #3653. I haven't read it in detail, but it seems like we should revert #3563 on master since there isn't any good option to prevent this bug right now.

**Comment by mishatatinets** [comment] 2016-01-02 23:53
Sean, thank you so much for clarification.

**Comment by ruslansavenok** [comment] 2016-01-04 09:26
With kaminari, you can make `views/kaminari/custom-pagination` and use: `<%= paginate @items, theme: 'custome-pagination'%>`

If you dont want to use `theme: ''` everywhere, you can create custom wrapper for paginate helper, or overwrite original helper in `application_helper` with `unless` block for active admin

**Comment by fredngo** [comment] 2016-02-22 03:34
I too am experiencing this, apparently due to customizing the Kaminari template to use bootstrap styles in my app.

**Comment by phoenixweiss** [comment] 2016-03-24 22:46
I have the same issue. Theming the front kaminari solves that stuck but it isn't so obvious.

**Comment by s2ugimot** [comment] 2016-06-13 08:51
+1 and hope this would be back-ported into 0.6-stable also

**Comment by yuki-takei** [comment] 2016-06-13 08:54
+1

**Comment by kouki-o** [comment] 2016-06-14 04:31
+1

**Comment by nowakov** [comment] 2016-07-02 17:14
+1

**Comment by mattgibson** [comment] 2016-11-15 13:07
Looks like https://github.com/amatsuda/kaminari/pull/668 has landed in the Kaminari master branch now. Should be fixable by namespacing the active admin pagination templates.

**Comment by spider-network** [comment] 2016-12-12 10:12
Is this really a blocker to the 1.0 release? I think **NO**! Please bump Version 1.0!!!

**Comment by jeyraof** [comment] 2017-01-03 09:14
Is this fixed?
I'm using `1.0.0.pre4`, but also broken.

<img width="213" alt="screen shot 2017-01-03 at 18 14 05" src="https://cloud.githubusercontent.com/assets/2032880/21603412/7564befe-d1e0-11e6-8738-2903474f1aa8.png">

**Comment by koenhandekyn** [comment] 2017-01-12 00:13
+1

**Comment by deivid-rodriguez** [comment] 2017-01-13 16:01
I'd like to ask where this is going, since the related kaminari PR does not seem to directly help with this issue. The idea is to provide a configuration to tell activeadmin to load a specific pagination theme, right?

**Comment by iBcker** [comment] 2017-02-13 06:27
same issue

i add custom style append to **active_admin.scss** fix it

`#index_footer>ul.pagination{
  li{
    display: inline;
  }
}`

**Closed** 2017-07-06 21:54 UTC
Labels: bug?, workaround

**Comment by javierjulio** [comment] 2017-07-07 01:50
I've added the default Kaminari templates in #5069 and merged into master. It will go out in a v1.1 release.
