### ISSUE TITLE
NoMethodError: undefined method `devise_error_messages!'

### ISSUE THREAD

**Issue by jlecour** [activeadmin/activeadmin#3780] opened 2015-02-05 14:20 UTC
Hi,

I'm using Devise (3.4.1) and ActiveAdmin (76f194ebe333) with an `AdminUser` model.

I get this error each time I display a Devise related form : 

    NoMethodError: undefined method `devise_error_messages!'

If I remove the call to this method, it works (obviously).

I wonder if it's is an issue with the `DeviseHelper` module that would not properly be included in the controller by ActiveAdmin.

**Comment by timoschilling** [comment] 2015-02-05 18:04
Could it be that you have turned of `include_all_helpers`?

**Comment by jlecour** [comment] 2015-02-05 19:49
Thanks @timoschilling

I don't see any reference to this method in the application.

**Comment by timoschilling** [comment] 2015-02-05 21:01
Please check this in the Rails console:
```ruby
Rails.application.config.action_controller.include_all_helpers
```

Or even better on the ActiveAdmin Dashboard:
```ruby
para Rails.application.config.action_controller.include_all_helpers.class
```

**Comment by jlecour** [comment] 2015-02-05 21:17
It returns `nil`

**Comment by timoschilling** [comment] 2015-02-06 08:48
`nil` it's the expected value. You can try to set it to `true` in your `application.rb`.

If that don't work, include the `DeviseHelper` by hand or provide a test app to reproduce this.

**Comment by timoschilling** [comment] 2015-03-15 17:05
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.

**Closed by timoschilling** 2015-03-15 17:05 UTC
