### ISSUE TITLE
Large associations cause long load times with default filters

### ISSUE THREAD

**Issue by onyxraven** [activeadmin/activeadmin#2738] opened 2013-11-26 22:54 UTC
In 0.6.2, has_many associations were added to the default filter list with this diff

https://github.com/gregbell/active_admin/compare/v0.6.0...v0.6.1#diff-182

For models that have an association whos table is very large, this causes very long load times AND n+1 issue as it tries to load each display_name.

I am currently monkey patching to revert to the old behavior:

``` ruby
module ActiveAdmin
  module Filters
    module ResourceExtension
      def default_filters
        default_content_filters
      end
    end
  end
end
```

but it would be great if this was a config option instead to turn on/off that behavior globally and per-controller.

[edit: ended up having to turn off all assoc filters and just use the content filters]

**Comment by ndbroadbent** [comment] 2020-05-18 10:06
This is my main problem with ActiveAdmin, so I would love to see a more sane default where the filters don't try to load every row from a table. This has caused problems at most of the companies I worked at over the last 10+ years, and also my current project. The default filters would lock up the entire application in production because it was trying to build a huge select list with every possible option, so I think this behavior should definitely be turned off or limited by default.

Making AJAX calls with Select2 would be really awesome!

**Comment by sunny** [comment] 2020-07-12 09:48
This looks like a duplicate of #2692. Changes in #5548 should be able to help a lot with this.

**Comment by yagudaev** [comment] 2020-08-27 23:28
So does PR #5548 pretty much solve the problem? Do we just need to change this line to have a sane default? https://github.com/activeadmin/activeadmin/pull/5548/files#diff-1233a76d21c87580d4f82ea1f8608274R296

**Comment by sunny** [comment] 2020-08-29 15:52
Yes, you can now add `config.maximum_association_filter_arity = 256` to your activeadmin configuration 🎉

**Comment by yagudaev** [comment] 2020-08-29 17:39
Why don’t we change that default to be enabled for all new ActiveAdmin installs?

**Comment by sunny** [comment] 2020-08-30 20:58
According to the code, `256` will be the default in a future version of ActiveAdmin. This is not yet the case presumably because this is a breaking change, so hopefully in 3.0 🎉

**Comment by yagudaev** [comment] 2020-08-31 21:25
@sunny is there a roadmap to v3? It would be nice to see a few more ambitious changes to AA at some point. There are a lot of interesting changes with view_compoent from github and stimulus reflex.

Mainly having AA be responsive and easier to theme/customize would be pretty amazing. Plus a few of those more complex user interactions.

**Comment by sunny** [comment] 2020-09-01 07:49
I am not a maintainer and am not aware of any roadmap, sorry 🤷‍♂️

Indeed theming and customization would be amazing! As this is a large project, I guess that any help moving things along (for example on #3862) would help the maintainers.

**Comment by deivid-rodriguez** [comment] 2020-09-09 11:02
Thanks @sunny, yes, that's pretty much the situation. We're shipping slow but steady improvements and that's as best as I can do right now. Help is always appreciated.

There's no roadmap for 3.0 at the moment since there's no too many breaking changes pending to be released. Maybe once webpack setup is more battle tested we can switch new applications to use that by default as well, and ship this two little default changes, plus the removal of pending deprecations, as ActiveAdmin 3.0.

**Comment by javierjulio** [comment] 2023-03-12 22:32
Don't rely on the default generated filters. Always declare the filters for each page to avoid issues like this.

**Closed by javierjulio** 2023-03-12 22:32 UTC
