### ISSUE TITLE
ActiveAdmin eats all my memory and freeze the computer

### ISSUE THREAD

**Issue by nleo** [activeadmin/activeadmin#5752] opened 2019-04-26 10:12 UTC
1. Install of AA 2.0.0 on rails 5.1.6.1
2. Download production DB
3. Generate  `rails generate active_admin:resource` for resouce with 152559 records
4. Try to open it in browser
5. I can see ruby2.5 process eats 4.8GiB in SystemMonitor before it stop responding
6. Hard reset

I have 7.7 GiB RAM and 7.9GiB Swap

**Comment by Fivell** [comment] 2019-04-26 11:58
@nleo maybe related to #2738 ?

**Comment by nleo** [comment] 2019-04-26 16:03
@Fivell maybe. If u give me simple steps to check it, I can do it.

For my self I decide to not use AA in my projects. So I will not do complex investigations

**Comment by bdeterling** [comment] 2019-04-29 16:19
Adding this information because this issue is so recent and it's the first result that shows up when I search for my particular issue. With ActiveAdmin installed (1.3 or 2.0), simply calling reload! in rails console, takes an increasing amount of time:

```
rails c
Loading development environment (Rails 5.2.3)
2.4.4 :001 > t = Time.now; reload!; Time.now-t
Reloading...
 => 1.328501337 
2.4.4 :002 > t = Time.now; reload!; Time.now-t
Reloading...
 => 2.303970236 
2.4.4 :003 > t = Time.now; reload!; Time.now-t
Reloading...
 => 3.685325292 
2.4.4 :004 > t = Time.now; reload!; Time.now-t
Reloading...
 => 4.390409116 
2.4.4 :005 > t = Time.now; reload!; Time.now-t
Reloading...
 => 5.870954009 
2.4.4 :006 > t = Time.now; reload!; Time.now-t
Reloading...
 => 6.782252123 
```

That was all done without actually changing any code. Without ActiveAdmin, the times are consistently under 1 second. I would expect it to take a little longer with AA, but not an increasing amount of time. We have about 50 AA models. I tried profiling it and the problem appears to be related to routes, but I can't pin down exactly where it occurs.

**Comment by deivid-rodriguez** [comment] 2019-04-29 16:28
I believe this is a development only memory leak that was fixed in rails. Can you try to reproduce with Rails 6.0.0.rc1?

**Comment by bdeterling** [comment] 2019-04-29 17:36
I can't get my project updated due to various dependency issues, but I will test it as soon as I can and report back. Do you have link to the issue for the Rails fix?

**Comment by deivid-rodriguez** [comment] 2019-04-29 19:07
I was thinking of [this issue](https://github.com/rails/rails/issues/32892), but it sounds like it has no resolution yeat, and it might not be the same thing anyways.

There's other PRs that have been merged and could maybe help, like https://github.com/rails/rails/pull/31442 or https://github.com/rails/rails/pull/35201.

**Comment by bdeterling** [comment] 2019-04-29 22:45
Using the patched DescendantsTracker from https://github.com/rails/rails/issues/32892#issuecomment-476254992, seems to fix the reload issue. I haven't tested thoroughly enough to say it's the one true fix, but it does seem likely that my issue is not caused by ActiveAdmin. However, I have another app that doesn't use AA and doesn't exhibit the problem so AA may be doing something that triggers the actual problem.

**Comment by deivid-rodriguez** [comment] 2019-04-30 06:49
That's great news, and it kind of makes sense since that patch fixes a memory leak with anonymous classes, and activeadmin makes heavy use of those.

I'm closing this, then!

**Comment by nleo** [comment] 2019-05-08 11:28
@deivid-rodriguez  Rails 6.0.0.rc1 same memory leak

**Comment by rafalwojcik** [comment] 2019-06-06 14:53
Any updates? I also have the same problem :/

**Comment by javierjulio** [comment] 2019-06-06 15:00
@nleo @rafalwojcik are either of you relying on default filters that may be loading large associations as to what @Fivell linked to as a possible related issue?

**Comment by Fivell** [comment] 2019-06-06 16:04
@nleo  mentioned this 
>> Generate rails generate active_admin:resource for resouce with 152559 records


in initializer we have this

```
 # By default the index screen includes a "Filters" sidebar on the right
  # hand side with a filter for each attribute of the registered model.
  # You can enable or disable them for all resources here.
  #
  # config.filters = true
```
@javierjulio  however https://activeadmin.info/1-general-configuration.html is not covering this case.

**Comment by javierjulio** [comment] 2019-06-06 18:17
@Fivell good catch, yes we should have that covered in the docs. At Jackpocket we don't rely on default filters anywhere specifically for that issue.

**Comment by DanielHeath** [comment] 2019-07-17 04:33
https://github.com/activeadmin/activeadmin/pull/5548 will fix that by not rendering large select boxes by default.

**Closed** 2023-03-12 06:52 UTC
