### ISSUE TITLE
Question on AA opensource effort and maintenance

### ISSUE THREAD

**Issue by emilebosch** [activeadmin/activeadmin#3774] opened 2015-01-29 22:20 UTC
Hi all, 
I love AA, its absolutely amazing. However i am wondering if its moving as fast as it can in terms of delivery of new features and solving issues. 

Ofcourse instead of complaining i should fork the thing and commit my stuff however i tried this and sorta ran into this seemingly complicated/hard to get through codebase. A couple things that stopped me from getting up to speed was:

- Cucumber/BDD
- ABRE (which makes sense in the dsl/when configuring but for every view its a bit hard to graps). Which also makes customising the whole layout hard. (i.e. can't just copy a couple of slim/erb files and get cracking)
- Super modulairity / tons of different modules etc etc.

Are other people also affected by this? Or is it just me. I was wondering if we could simplify things so that its easier for other contributors to join as well. Please provide feedback on what you think.

**Comment by emilebosch** [comment] 2015-01-29 22:41
Actually I might take it back I'm starting to wonder if there actually _is_ another to simplify this. It might just be complicated.

**Comment by dmitry** [comment] 2015-01-31 00:40
I don't like abre, because I'm more on the client side for the templates, like react. But other things just help to make project alive, like BDD and Cucumber preventing from the regressions (similar to the rails unit tests - it's most general point why rails is still used by many developers - few regressions between the versions), modularity gives ability to test everything. Some modules very coupled with others, but that's maybe fixed by whom doesn't like that ;)

**Comment by timoschilling** [comment] 2015-02-02 14:19
I's sharing the meaning of @dmitry. The Arbre view should be more configurable and better documented, there is already a issue for that #3517.

The main construct of active admin, would not be changed.

**Closed by timoschilling** 2015-02-02 14:19 UTC
