### ISSUE TITLE
Incorrectly generated files when installing AA with webpacker from a template.

### ISSUE THREAD

**Issue by OrceMaceski** [activeadmin/activeadmin#6468] opened 2020-09-22 17:43 UTC
When starting new rails app from a template with pre-configured active admin through webpacker, files (package.json, yarn.lock, node_modules) are generated outside the app.
Repro steps:
Create a basic **template.rb**
```
gem 'activeadmin'
gem 'devise'

after_bundle do
  generate 'active_admin:install --use-webpacker'
end
```
Create new rails app using **template.rb**

**Comment by deivid-rodriguez** [comment] 2020-09-24 17:37
Hi @OrceMaceski!

This seems like a problem caused by [a recent change in spring](https://github.com/rails/spring/pull/621).

You can verify this by either generating the app without `spring` (`rails new --skip-spring --template template.rb foo`), or by forcing the previous working version of `spring`, changing the template to:

```ruby
gem 'activeadmin'
gem 'devise'
gsub_file 'Gemfile', /gem 'spring'.*/, "gem 'spring', '2.1.0'"

after_bundle do
  generate 'active_admin:install --use-webpacker'
end
```

I'll try to workaround this on our side, so that it still works with the latest `spring`.

**Comment by deivid-rodriguez** [comment] 2020-10-12 19:01
Hi again @OrceMaceski.

I discovered that the offending PR in spring broke some spring specs in addition to our particular use case here, and the original PR's author propose to revert the PR until a better solution is found. So it seems like we won't need to change anything in activeadmin. You can ping to 2.1.0 for now, and once the revert is merged and release, you'll be able to safely upgrade to 2.1.2.

So, I'll close this ticket given the above :+1:.

**Closed by deivid-rodriguez** 2020-10-12 19:01 UTC
Labels: bug
