### ISSUE TITLE
has_one vs has_many: how to remove "Add new" when nested object already exists in edit form.

### ISSUE THREAD

**Issue by laclance** [activeadmin/activeadmin#4976] opened 2017-05-25 12:06 UTC
When using nested inputs with a has_one association i used this issue: https://github.com/activeadmin/activeadmin/issues/4614 to remove the  "Add new" and "Remove" buttons when creating. However when editing an item that already contains a nested object the "Add New" is there from the start and i cant figure out how to remove it. Any help would be appreciated please.

**Comment by pavel-jurasek-bcgdv-com** [comment] 2017-06-02 06:31
@laclance see my comment https://github.com/activeadmin/activeadmin/issues/4614

**Comment by Fivell** [comment] 2017-06-11 14:31
duplicate for #4415 ?

**Comment by varyonic** [comment] 2018-09-20 20:15
I think this is a duplicate of #4614 which includes [this workaround](https://github.com/activeadmin/activeadmin/issues/4614#issuecomment-336416764). Please feel free to leave a comment requesting this issue be reopened if needed.

**Closed by varyonic** 2018-09-20 20:15 UTC
