### ISSUE TITLE
Trix editor 

### ISSUE THREAD

**Issue by emcoding** [activeadmin/activeadmin#5643] opened 2018-12-12 16:05 UTC
[Please follow the guidelines for creating a bug report](https://github.com/activeadmin/activeadmin/blob/master/CONTRIBUTING.md#4-did-you-find-a-bug).

The issue tracker is only for bugs and feature requests. If you need general
help please post to
[StackOverflow](http://stackoverflow.com/questions/tagged/activeadmin).

### Expected behavior

I like to use the Trix editor (part of Rails 6), but the Active Admin forms don't recognize the `f.trix_editor` input, nor `f.input :something, as: :trix_editor`. Is that a Formtastic thing or a AA thing? 

### Actual behavior

`f.input :thing, as: :trix_editor` throws an Formtastic::UnknownInput Error.  
`f.trix_editor :thing` throws an ArgumentError (wrong number of arguments, given 1 expected 0)

### How to reproduce

Your best chance of getting this bug looked at quickly is to provide an
**executable test case** demonstrating the expected behavior that is not
occurring. [Please follow the guidelines for creating a bug
report](https://github.com/activeadmin/activeadmin/blob/master/CONTRIBUTING.md#4-did-you-find-a-bug).

**Comment by ch000** [comment] 2018-12-12 23:52
`f.rich_text_area :something` is working for me.

**Comment by Mgitim** [comment] 2019-06-21 06:50
@ch000 This is working for you in Active admin or in a regular .html.erb file?

**Comment by victorbstan** [comment] 2019-10-30 22:18
Is there any news on this? I'd like to enable `rich_text_area` in admin inputs as well

**Comment by victorbstan** [comment] 2019-10-31 16:38
OK cool, that seems pretty standard. 

I think I've moved the stylesheets and JS for active admin in the `vendors` folders because it was clashing with the rest of the app styling, and I have to figure out how to get the trix styling and JS files to be available for active admin again.

**Comment by Mgitim** [comment] 2019-10-31 18:47
@victorbstan hmmmm, if you are using active admin, you wouldn't have to move anything in to 'vendors'. Your stylesheet would go in to app/assets/stylesheets/active_admin.scss and your js would go under app/assets/javascript/active_admin.js. Unless you import those files into your application.js or application.scss, you shouldn't have any clashing. To get trix styling in your active admin css file import it as such. @import "trix/dist/trix";
Hope it helps.

**Comment by victorbstan** [comment] 2019-10-31 19:18
By default rails seems to load the all the assets from the asset folder together. I did not change the default Rails 6 behaviour.

This is default rails application.css

```
 *= require_tree .
 *= require_self
```

If active admin stylesheet was in the stylesheets folder, would it not interfere with the other styles?

Cheers,
Victor Stan

**Comment by rosendi** [comment] 2019-12-02 21:38
Rails (6) fails with:

```
undefined method `rich_text_area_tag' for #<#<Class:0x00007fb14894fda8>:0x00007fb14895e470>
Did you mean?  rich_text_area
```

```
  form do |f|
    f.semantic_errors

    f.rich_text_area :text

    f.inputs 'Text' do
      input :link_href
      input :link_text
    end

    f.actions
  end
```

Any thoughts?

**Comment by dmitry** [comment] 2019-12-02 23:17
@rosendi what was an error?

**Comment by rosendi** [comment] 2019-12-02 23:36
@dmitry

```
undefined method `rich_text_area_tag' for #<#<Class:0x00007fb14894fda8>:0x00007fb14895e470>
Did you mean?  rich_text_area
```

Looks like the `rich_text_area` method uses `rich_text_area_tag` internally, but it's undefined in the ActiveAdmin scope. However in my Rails app (not admin scope) everything works fine.

**Comment by rosendi** [comment] 2019-12-04 02:17
No idea?

**Comment by dmitry** [comment] 2019-12-07 11:32
@rosendi I suggest you to use debugger to find out where it is trying to be called. Check if `rich_text_area` is called from the https://github.com/rails/rails/blob/530f7805ed5790af1d472a041bc74089dc183f47/actiontext/app/helpers/action_text/tag_helper.rb#L21.

**Comment by rosendi** [comment] 2019-12-07 11:42
I think the issue is with Zeitwerk. Still investigating. The temporary fix is to include actiontext's helpers in ApplicationController:

```
class ApplicationController < ActionController::Base
  helper ActionText::Engine.helpers
```

Technically it should be automatically included through `application.rb`:

```
require_relative 'boot'

require "rails"
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
require "active_storage/engine"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_mailbox/engine"
require "action_text/engine" <-----------------
require "action_view/railtie"
require "action_cable/engine"
require "rails/test_unit/railtie"
require "sprockets/railtie"
```

**Comment by victorbstan** [comment] 2019-12-07 14:11
Thanks, if it’s supposed to work I’ll figure out why it doesn’t, it might be a few weeks before I get back on that project. I just wanted to know if it’s supported at least. 

Cheers,
Victor Stan

**Comment by dmitry** [comment] 2019-12-08 13:33
Means this initializer is not running?

https://github.com/rails/rails/blob/530f7805ed5790af1d472a041bc74089dc183f47/actiontext/lib/action_text/engine.rb#L35

**Comment by swiknaba** [comment] 2020-01-13 12:09
adding this gem: https://rubygems.org/gems/active_admin_trix
and following its documentation: https://www.rubydoc.info/gems/active_admin_trix/0.0.3
solved the issue for me.

The steps are:
- routes.rb: `gem 'active_admin_trix', '~> 0.0.3'`
- initializers/active_admin.rb:
```ruby
  # @NOTE: see: https://www.rubydoc.info/gems/active_admin_trix/0.0.3
  # config.register_stylesheet 'https://cdn.bootcss.com/trix/1.0.0/trix.css'
  # config.register_javascript 'https://cdn.bootcss.com/trix/1.0.0/trix.js'
  # more up-to-date libraries: https://cdnjs.com/libraries/trix
  config.register_stylesheet 'https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.css'
  config.register_javascript 'https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.js'
```

- in your app/admin/my_models.rb:
```ruby
form do |f|
  f.inputs do
    # @NOTE: the docs suggest `f.input :content, as: :trix` which did render the trix-editor, but it did not fill in the text if there was already some available from the database
    f.rich_text_area :content
  end
end
```

**Comment by rosendi** [comment] 2020-01-13 15:06
@swiknaba you don't need an additional gem. Trix works with ActiveAdmin out of the box.

**Comment by rosendi** [comment] 2020-01-13 15:08
There is still a weird issue with Zeitwerk, but it affects only a certain environments with specific conditions.

**Comment by rosendi** [comment] 2020-01-13 15:09
> Means this initializer is not running?
> 
> https://github.com/rails/rails/blob/530f7805ed5790af1d472a041bc74089dc183f47/actiontext/lib/action_text/engine.rb#L35

yep, looks so

**Comment by swiknaba** [comment] 2020-01-13 15:35
Thanks for the reply @rosendi . At least locally, it did not work out of the box for me, I haven't tested it in `production` environment yet just `development`. I tried to include that mentioned helper via

```ruby
# app/admin/my_models.rb
ActiveAdmin.register MyModel do
  controller do
    helper ActionText::Engine.helpers
  end
end
```

without success. Of course, possibly, I have other errors in my codebase causing the trouble.

**Comment by Piyush-Chaudhary** [comment] 2020-09-05 20:52
> Yep. I will create a demo repo.

Have you created it?

**Comment by blocknotes** [comment] 2020-09-19 16:40
Recently I was making the same experiment.
Here it is a gist to make Trix works with ActiveAdmin (without extra gems):
https://gist.github.com/blocknotes/74baceccc74c12c60a60a42d112787a3

**Comment by pauloFernandes** [comment] 2020-09-28 15:19
It worked for me, as @blocknotes sad in his gist.

> https://gist.github.com/blocknotes/74baceccc74c12c60a60a42d112787a3

But I have a problem when trying to use this in a has_many nested form

```rb
forms do |f|
  f.inputs 'General' do
    f.input :name
    f.rich_text_area :description # this one works like a charm
  end

  f.inputs 'Steps' do 
    f.has_many :steps do |step|
      s.input :name
      s.rich_text_area :details # this one not even renders the component
    end
  end
end
```

My step.details input doesn't render anything, not even its `<li />`

**Comment by blocknotes** [comment] 2020-09-29 07:39
> But I have a problem when trying to use this in a has_many nested form
...
>     f.has_many :steps do |step|
>       s.input :name
>       s.rich_text_area :details # this one not even renders the component
>     end

I think that `has_many` still doesn't support Arbre elements.
Reference comment [here](https://github.com/activeadmin/activeadmin/issues/4043#issuecomment-285876541).

**Comment by kwent** [comment] 2020-11-12 05:17
Does anyone has figure out how to support active storage image upload ?

**Comment by nazrulcse** [comment] 2022-05-25 03:49
Rails 7 seems not working showing "Uncaught SyntaxError: Unexpected token 'export'" when require trix in active_admin.js
//=require trix

**Comment by javierjulio** [comment] 2023-03-12 21:59
Closing in favor of #6106

**Closed by javierjulio** 2023-03-12 21:59 UTC
