### ISSUE TITLE
Problem showing form at active admin custom page using admin active_admin_form_for

### ISSUE THREAD

**Issue by sadaf2605** [activeadmin/activeadmin#4086] opened 2015-08-20 18:48 UTC
I am trying to use active_admin_form for showing form in active admin custom page:

```
ActiveAdmin.register_page "featuredproduct" do
content do
    active_admin_form_for @item do |f|
         f.semantic_fields_for [:product, f.object.product || Product.new] do |p|
             p.input :manufacturer
             p.input :part_no
             p.has_many :market_statuses, for: [:market_statuses,  p.object.market_statuses || MarketStatus.new],allow_destroy: true do |a|
                  a.input :price
                  a.inputs :shop
             end
        end
     end
 end
```

is embeding following:

```
<form novalidate="novalidate" class="formtastic cpu" id="edit_cpu_5" action="/cpus/5" accept-charset="UTF-8" method="post"><input name="utf8" value="✓" type="hidden"><input name="_method" value="patch" type="hidden"><input name="authenticity_token" value="uZKv6PkdjdzHdrRksktCXDHrfRwXyEHq0V0Q2Dj/Ebjut/QUeDPTpWQuUtwxkDpgkX2/cMp8rp3iKOdtaMFXAA==" type="hidden"><div class="has_many_container market_statuses" data-sortable-start="0"><h3>Market status</h3><a class="button has_many_add" data-html="<fieldset class=&quot;inputs has_many_fields&quot;><ol><li class=&quot;number input optional numeric stringish&quot; id=&quot;cpu_product_market_statuses_attributes_NEW_MARKET_STATUS_RECORD_price_input&quot;><label for=&quot;cpu_product_market_statuses_attributes_NEW_MARKET_STATUS_RECORD_price&quot; class=&quot;label&quot;>Price</label><input id=&quot;cpu_product_market_statuses_attributes_NEW_MARKET_STATUS_RECORD_price&quot; step=&quot;any&quot; type=&quot;number&quot; name=&quot;cpu[product][market_statuses_attributes][NEW_MARKET_STATUS_RECORD][price]&quot; />

</li><li class=&quot;select input optional&quot; id=&quot;cpu_product_market_statuses_attributes_NEW_MARKET_STATUS_RECORD_shop_input&quot;><label for=&quot;cpu_product_market_statuses_attributes_NEW_MARKET_STATUS_RECORD_shop_id&quot; class=&quot;label&quot;>Shop</label><select name=&quot;cpu[product][market_statuses_attributes][NEW_MARKET_STATUS_RECORD][shop_id]&quot; id=&quot;cpu_product_market_statuses_attributes_NEW_MARKET_STATUS_RECORD_shop_id&quot;><option value=&quot;&quot;></option>
<option value=&quot;1&quot;>A b shop</option></select>

</li><li><a class=&quot;button has_many_remove&quot; href=&quot;#&quot;>Remove</a></li></ol></fieldset>" data-placeholder="NEW_MARKET_STATUS_RECORD" href="#">Add New Market status</a></div></form>
```

So only thing I could see is an `add market status` button. I could not see fields for 

```
p.input :manufacturer 
p.input :part_no
```

**Comment by varyonic** [comment] 2017-03-25 19:10
@sadaf2605 Did you figure this out?  I don't think active_admin_form_for was intended to be used or tested for custom pages.

**Comment by varyonic** [comment] 2018-09-20 17:50
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.

**Closed by varyonic** 2018-09-20 17:50 UTC
Labels: forms
