### ISSUE TITLE
Adding action cable features to dsl

### ISSUE THREAD

**Issue by marcomd** [activeadmin/activeadmin#4311] opened 2016-02-09 17:26 UTC
Are you planning to add any new action cable feature to active admin?
Something like:

``` ruby
ActiveAdmin.register Message do
  channel_room :speak do |data|
    Message.create! content: data['message']
  end
end  
```

The coffeescript should be handled manually i think

**Comment by timoschilling** [comment] 2016-02-09 22:53
I don't think so

**Comment by seanlinsley** [comment] 2016-02-13 23:37
Action Cable could be useful for:
- CSV generation
- mass import (#2421)
- batch actions applied to the whole collection (instead of to the first page like it currently does)
- notifying the user that a background job (Resque, Sidekiq, etc.) finished

The problem is, we'd then need some adapter to support multiple types of background workers. Or a simple first version could open a single thread that ActiveAdmin controlled, instead of relying on libraries like Resque and Sidekiq.

But either way, that's a lot of work. If someone wants to add features like this, I'd be willing to review their PRs.

But your actual question is about adding a simple DSL to handle ActionCable from inside ActiveAdmin. The existing DSL that Rails provides is pretty simple, so I don't think we need to simplify it further: https://github.com/rails/rails/tree/master/actioncable

**Comment by marcomd** [comment] 2016-02-15 08:28
Thanks for the answers.

With aa we do not write html code so I wonder how to do the same with activecable. The issue is not make it easier, but stay consistent.

**Comment by varyonic** [comment] 2017-05-03 15:13
I propose closing, we have discussed CSV import/export and background jobs elsewhere, probably best as a plugin.

**Comment by javierjulio** [comment] 2017-07-05 19:18
Agree with @varyonic on this.

**Closed by javierjulio** 2017-07-05 19:18 UTC
