### ISSUE TITLE
Problem with a few Active admin JS components after upgrade

### ISSUE THREAD

**Issue by srihere17** [activeadmin/activeadmin#5124] opened 2017-08-05 06:24 UTC
Hi,

We recently have upgraded our rails version to 5.1.3. It also had upgraded the Active admin version to 1.1.
After upgrade, we are getting a few errors on components like Form tabs, Checkbox components, batch actions in Index view etc.,. It is throwing JS errors as shown below.

![image](https://user-images.githubusercontent.com/30743253/28993271-51c42b9a-79d0-11e7-95ce-a8ff6a6bd3f9.png)

Did anyone else faced this issue?

### Expected behavior

The components should be working as earlier before the upgrade

### Actual behavior

A few of the UI components are failing.

### How to reproduce

Upgrade the Rails and Active admin versions

**Comment by vraravam** [comment] 2017-08-05 14:17
I have also faced the same issue - downgrading AA to v1.0 fixed the issue. but, I need some of the new bug fixes/functionalities that AA 1.1 gives - please fix asap!

**Comment by javierjulio** [comment] 2017-08-05 14:42
Can you please provide an app that replicates the issue? It will help us review this quickly. I haven't had any problems after upgrading in regards to this. I suspect some configuration around assets might be the cause. Again an app that replicates the issue will help us review this. Also the error is in regards to a method provided by jQuery UI. Do you see the jQuery UI code being loaded?

**Comment by varyonic** [comment] 2018-09-21 15:05
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.

**Closed by varyonic** 2018-09-21 15:05 UTC
