### ISSUE TITLE
SassC::SyntaxError: Error: Undefined variable: "$primary-color".

### ISSUE THREAD

**Issue by sharat-hegde** [activeadmin/activeadmin#6392] opened 2020-08-12 13:18 UTC
i am getting this error while doing precompile

SassC::SyntaxError: Error: Undefined variable: "$primary-color".
        on line 33:10 of ../../.rvm/gems/ruby-2.5.0@project/gems/activeadmin-2.4.0/app/assets/stylesheets/active_admin/_typography.scss
        from line 6:9 of ../../.rvm/gems/ruby-2.5.0@project/gems/activeadmin-2.4.0/app/assets/stylesheets/active_admin/_base.scss
>>   color: $primary-color;

**Comment by deivid-rodriguez** [comment] 2020-08-24 09:43
Closing as duplicate of #5933.

**Closed by deivid-rodriguez** 2020-08-24 09:43 UTC
