### ISSUE TITLE
Why there is no secondary action menu for custom forms

### ISSUE THREAD

**Issue by liurui12w** [activeadmin/activeadmin#5742] opened 2019-04-15 02:21 UTC
Why there is no secondary action menu for custom forms

cascading menu

Similar to cities and regions, cities are first-level drop-down and second-level districts. Select first-level and second-level districts to screen specific values.

![image](https://user-images.githubusercontent.com/19525490/56135090-946d5c80-5fc2-11e9-9fbc-3027f602193b.png)

**Comment by Fivell** [comment] 2019-04-26 11:59
duplicate of #2440

**Comment by liurui12w** [comment] 2019-04-28 11:48
> duplicate of #2440

thanks

**Closed** 2019-04-28 12:14 UTC
