### ISSUE TITLE
Crash on new resource page

### ISSUE THREAD

**Issue by deivid-rodriguez** [activeadmin/activeadmin#4897] opened 2017-04-05 14:30 UTC
This seems to have been introduced by #4477.

Posting here reproduction instructions for @Fivell :wink: 

* git clone https://github.com/EnComu/participa
* cd participa
* Follow development setup instructions [here](https://github.com/EnComu/participa/#instalaci%C3%B3n). I'm sorry we don't have something fully automatized. There's also a docker setup, but it hasn't been used in a while, you might want to try that as well. This is a standard Rails application.
* After setup, edit Gemfile to stop pinning activeadmin to the revision prior to #4477, and rebundle.
* Start the application, login with the test admin account (user: admin@example.com, pass: 111111), and visit http://localhost:3000/admin/verification_centers/new.

The app should crash.

I'm sorry I don't have the time to provide a more isolated example at the moment...

**Comment by Fivell** [comment] 2017-04-06 13:26
```
 
actionview (5.0.2) lib/action_view/helpers/controller_helper.rb:10:in `rescue in action_name'
actionview (5.0.2) lib/action_view/helpers/controller_helper.rb:10:in `action_name'
arbre (1.1.1) lib/arbre/rails/forms.rb:30:in `proxy_call_to_form'
arbre (1.1.1) lib/arbre/rails/forms.rb:35:in `method_missing'
/Users/igor/Projects/ruby/gems/activeadmin/lib/active_admin/views/components/active_admin_form.rb:81:in `add_create_another_checkbox'
/Users/igor/Projects/ruby/gems/activeadmin/lib/active_admin/views/components/active_admin_form.rb:75:in `commit_action_with_cancel_link'
/Users/igor/Projects/ruby/gems/activeadmin/lib/active_admin/views/components/active_admin_form.rb:71:in `block in actions'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
/Users/igor/Projects/ruby/gems/activeadmin/lib/active_admin/views/components/active_admin_form.rb:70:in `actions'
/Users/igor/Projects/ruby/gems/activeadmin/lib/active_admin/views/components/active_admin_form.rb:71:in `actions'
/Users/igor/Projects/ruby/gems/activeadmin/lib/active_admin/views/pages/form.rb:46:in `block in default_form_config'
/Users/igor/Projects/ruby/gems/activeadmin/lib/active_admin/views/components/active_admin_form.rb:35:in `instance_eval'
/Users/igor/Projects/ruby/gems/activeadmin/lib/active_admin/views/components/active_admin_form.rb:35:in `build'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:28:in `block in build_tag'
arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:14:in `active_admin_form_for'
/Users/igor/Projects/ruby/gems/activeadmin/lib/active_admin/views/pages/form.rb:25:in `main_content'
/Users/igor/Projects/ruby/gems/activeadmin/lib/active_admin/views/pages/base.rb:93:in `block (2 levels) in build_main_content_wrapper'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:14:in `div'
/Users/igor/Projects/ruby/gems/activeadmin/lib/active_admin/views/pages/base.rb:92:in `block in build_main_content_wrapper'

```
looks like 

```
  def add_create_another_checkbox
        if %w(new create).include?(action_name) &&  active_admin_config && active_admin_config.create_another
          current_arbre_element.add_child(create_another_checkbox)
        end
      end

```

should be changed to 

```
  def add_create_another_checkbox
        if %w(new create).include?(helpers.action_name) &&  active_admin_config && active_admin_config.create_another
          current_arbre_element.add_child(create_another_checkbox)
        end
      end

```

**Comment by Fivell** [comment] 2017-04-06 13:34
@deivid-rodriguez , I updated demo.activeadmin locally to last AA commit and can't reproduce this bug, so I don't know if it is AA issue

**Comment by deivid-rodriguez** [comment] 2017-04-06 13:41
Does the patch you posted here fix it? I was certainly not expecting that this reproduced on our small sample app, we would've noticed earlier if that was the case.

Not sure either if this is AA bug or not but that PR certainly broke our "new verification center" page. Of that I'm sure! :)

**Comment by Fivell** [comment] 2017-04-06 13:49
@deivid-rodriguez , in your app  new and edit forms doesn't work, not only "new verification center" Yes after patch problem disappears and forms work,  however still can't reproduce it in another app, feature tests in AA also looks good for me, so it may be not AA itself but something else.

**Comment by deivid-rodriguez** [comment] 2017-04-06 13:54
Ah, ok! So the situation is even worse... That's useful info, maybe something with our configuration then? I just found this in our `config/initializers/active_admin.rb`.

```
ActiveAdmin::Views::SidebarSection.class_eval do
  def build(section)
    @section = section
    super(@section.title)
    self.id = @section.id
    build_sidebar_content
  end
end
```

Looks like something very likely to break...

**Comment by deivid-rodriguez** [comment] 2017-04-06 14:09
Is the change you suggested a good change, regardless of the bug?

**Comment by Fivell** [comment] 2017-04-06 15:02
@deivid-rodriguez , in case you have idea how to create failing spec

**Comment by Fivell** [comment] 2017-04-06 18:20
@varyonic ,  maybe we need to add ```action_item```  delegation [here](https://github.com/activeadmin/activeadmin/pull/4797/files#diff-1ca3d5d936ee4939e354692f648b27e2R15)

However I don't understand why this can't be reproduced with our feature tests

**Comment by varyonic** [comment] 2017-04-06 20:54
Maybe.  The [earlier suggestion](https://github.com/activeadmin/activeadmin/issues/4897#issuecomment-292173935) looks good.

**Comment by deivid-rodriguez** [comment] 2017-04-18 02:40
I researched this a bit. The problem seems to be caused by a third party gem, `simple_captcha2`, which [monkey-patches the standard Rails form builder](https://github.com/pludoni/simple-captcha/blob/b145495ab9e5a41da02667ca4e031b7ca1b1bb98/lib/simple_captcha/engine.rb#L14) and [includes a lot of extra stuff in it](https://github.com/pludoni/simple-captcha/blob/c4cd847063c7e743db759ada0160a66c0532d489/lib/simple_captcha/form_builder.rb#L6). In particular, the `action_name` method making this crash.

This should be fixed inside `simple_captcha2`, but I still wonder whether the earlier suggestion is a good change regardless of this problem.

**Comment by deivid-rodriguez** [comment] 2017-04-19 22:25
I made a temporary fix in my `simple_captcha2` fork (https://github.com/deivid-rodriguez/simple-captcha/commit/c9b960d3ae1a04ba899fc32d7be53c41b6f58c6d).

I guess we can close this, but we should consider whether

```diff
 def add_create_another_checkbox
-  if %w(new create).include?(action_name) &&  active_admin_config && active_admin_config.create_another
+  if %w(new create).include?(helpers.action_name) &&  active_admin_config && active_admin_config.create_another
     current_arbre_element.add_child(create_another_checkbox)
   end
 end
```

could make AA more resiliente to this kind of problems.

**Comment by Fivell** [comment] 2017-04-20 10:08
@deivid-rodriguez , I don't mind this patch to be merged

**Closed** 2017-04-22 11:24 UTC
