### ISSUE TITLE
ActiveAdmin causes failures for google-api-client

### ISSUE THREAD

**Issue by jostster** [activeadmin/activeadmin#4707] opened 2017-01-03 02:12 UTC
https://developers.google.com/drive/v3/web/quickstart/ruby

Using the google-api-client with active admin causes SSL errors like ```Faraday::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A```

I have all the proper certs installed. If I remove activeadmin and run the rake task without activeadmin it runs without errors. Once ActiveAdmin is installed, the above errors show.

Rails: 4.2.7.1
Ruby 2.3.1p112
ActiveAdmin 1.0.0pre4

**Comment by varyonic** [comment] 2017-01-04 19:23
Searching StackOverflow my guess is this is related to ActiveAdmin using Coveralls, depending on RestClient that defaults to a now outdated SSLv3.  I'm not able to reproduce but my guess is the workaround will be related to changing the RestClient SSL configuration or avoiding Coveralls. http://stackoverflow.com/search?q=ssl+syscall+5

**Comment by jostster** [comment] 2017-01-04 19:28
@varyonic Can you give some examples? I'm not sure what you are saying. I created a fresh rails activeadmin then added the `google-api-client` gem and ran the rake task. Same issue occurred on a fresh install. Once I removed the activeadmin gem, the rake ran fine.

I'm not sure how to change the SSL Config.

**Comment by varyonic** [comment] 2017-01-04 20:07
Changing SSL config is not really an ActiveAdmin issue.   You will find plenty of help on StackOverflow, eg. http://stackoverflow.com/questions/31358003/syscall-returned-5-errno-0-state-sslv3-read-server-hello-a-with-ruby-restful-cli

**Comment by jostster** [comment] 2017-01-04 20:22
I guess I'm confused on why this isn't an activeadmin issue since, activeadmin is the one causing the issue when installed.

**Comment by varyonic** [comment] 2017-01-04 20:33
Try OpenSSL::SSL::SSLContext::DEFAULT_PARAMS[:ssl_version] = 'TLSv1_2' before calling the Google API.

**Comment by jostster** [comment] 2017-01-04 20:39
@varyonic i appreciate you helping. However doing what you said above as well as the linked article still displays the error but with the state changing from SSLv2/3 to just SSLv3.

**Comment by varyonic** [comment] 2017-01-04 20:50
Add OpenSSL::SSL::SSLContext::DEFAULT_PARAMS[:ciphers] = ''RC4-SHA'?  Suggested [here] (http://stackoverflow.com/questions/25814210/opensslsslsslerror-ssl-connect-syscall-returned-5-errno-0-state-sslv3-read)

**Comment by jostster** [comment] 2017-01-04 21:20
I did some debugging and WITHOUT the activeadmin gem installed I did a puts on the DEFAULT_PARAMS. This is what it was 
```
{:ssl_version=>"SSLv23", :verify_mode=>1, :ciphers=>"ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-DSS-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:DHE-DSS-AES128-SHA256:DHE-DSS-AES256-SHA256:DHE-DSS-AES128-SHA:DHE-DSS-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:ECDHE-ECDSA-RC4-SHA:ECDHE-RSA-RC4-SHA:RC4-SHA", :options=>-2097019905}
```
With activeadmin it was the below
```
{:ssl_version=>"SSLv23", :verify_mode=>1, :ciphers=>"ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-DSS-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:DHE-DSS-AES128-SHA256:DHE-DSS-AES256-SHA256:DHE-DSS-AES128-SHA:DHE-DSS-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:ECDHE-ECDSA-RC4-SHA:ECDHE-RSA-RC4-SHA:RC4-SHA", :options=>-2097019905}
```

Notice they are the same. Without activeadmin installed the test of

```
require 'google/apis/drive_v3'
require 'googleauth'
require 'googleauth/stores/file_token_store'

require 'fileutils'

OOB_URI2 = 'urn:ietf:wg:oauth:2.0:oob'
APPLICATION_NAME2 = 'Google Sync'
CLIENT_SECRETS_PATH2 = 'client_config.json'
CREDENTIALS_PATH2 = File.join(Dir.home, '.credentials', "g-sync.yaml")
SCOPE2 = Google::Apis::DriveV3::AUTH_DRIVE_FILE


task :google_test do


##
## Ensure valid credentials, either by restoring from the saved credentials
## files or intitiating an OAuth2 authorization. If authorization is required,
## the user's default browser will be launched to approve the request.
##
## @return [Google::Auth::UserRefreshCredentials] OAuth2 credentials
  def authorize
    FileUtils.mkdir_p(File.dirname(CREDENTIALS_PATH2))

    client_id = Google::Auth::ClientId.from_file(CLIENT_SECRETS_PATH2)
    token_store = Google::Auth::Stores::FileTokenStore.new(file: CREDENTIALS_PATH2)
    authorizer = Google::Auth::UserAuthorizer.new(
        client_id, SCOPE2, token_store)
    user_id = 'default'
    credentials = authorizer.get_credentials(user_id)
    if credentials.nil?
      url = authorizer.get_authorization_url(
          base_url: OOB_URI2)
      puts "Open the following URL in the browser and enter the " +
               "resulting code after authorization"
      puts url
      code = gets
      credentials = authorizer.get_and_store_credentials_from_code(
          user_id: user_id, code: code, base_url: OOB_URI2)
    end
    credentials
  end
  puts OpenSSL::SSL::SSLContext::DEFAULT_PARAMS
# Initialize the API
  Drive = Google::Apis::DriveV3 # Alias the module
  drive = Drive::DriveService.new

  drive.client_options.application_name = APPLICATION_NAME2
  drive.authorization = authorize

# Upload a file
# Instead of passing a name for a file on the file system, create a pseudo file from a string
  file_contents = StringIO.new(<<FILE_CONTENTS)
Field1,Field2,Field3
Some,Useless,Data
More,Useless,Info
FILE_CONTENTS

  parent_folder_id = 'folderID'
  new_file = Drive::File.new(name: 'Test Upload CSV', parents: [parent_folder_id])
  new_file = drive.create_file(new_file, upload_source: file_contents, content_type: 'text/csv')

  puts "File '#{new_file.name}' created with id '#{new_file.id}'. Folder Location: https://drive.google.com/drive/folders/#{parent_folder_id}"

end
```
works fine

gemfile
```
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.7.1'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.13', '< 0.5'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'activeadmin', github: 'activeadmin'
gem 'certified'
gem 'google-api-client'


# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

**Comment by varyonic** [comment] 2017-01-11 15:25
This might be fixed by #4721 which removes Coveralls, possibly the source of the conflict.

**Comment by jostster** [comment] 2017-01-12 01:47
I just did a `bundler update activeadmin` which pulled latest master `c99ac55b54053572778b15a1fd0af84fc0ae6d4c` and the same errors still appear. I added more context a few days back above.

**Comment by timoschilling** [comment] 2017-01-12 08:33
@varyonic coveralls was a development dependency, which is not loaded into the active admin using app, so I don't think that this issues are related

**Comment by jostster** [comment] 2017-01-12 18:33
@timoschilling thanks for the confirmation. Do you have an idea which part of active admin is conflicting with this?

**Comment by timoschilling** [comment] 2017-01-12 18:44
No I don't

**Comment by Fivell** [comment] 2017-01-12 19:22
@varyonic , I think if @jostster  could share minimal app that reproduce this bug that would  be helpful

**Comment by jostster** [comment] 2017-01-12 20:03
@Fivell I added the gemfile above. All I did was add that to a new rails app and run the above rake task. You will have to generate your own google drive api keys though.

**Comment by Fivell** [comment] 2017-01-12 20:07
@jostster , did you follow instructions  from this issue https://github.com/google/google-api-ruby-client/issues/253 ?

**Comment by jostster** [comment] 2017-01-12 20:10
@Fivell The issue isn't the certs, but yes I did update the certs anyways. I am also using the `certified` gem which fixes that and does it for me. To duplicate the issue, just do the above listed. Then to make the google-api work, comment out the `gem 'activeadmin'` and run `bundle install` again. Then run the rake. The upload will complete just fine.

**Comment by Fivell** [comment] 2017-01-12 20:43
@jostster , sorry I can't reproduce this, I used secrets from here https://github.com/google/google-api-ruby-client/edit/master/spec/fixtures/files/client_secrets.json and upload was success .

**Comment by Fivell** [comment] 2017-01-12 20:50
without parent_folder_id
 rake google_test

> /Users/igor/Projects/ruby/test_ga/test_ga/lib/tasks/client_config.json
> {:ssl_version=>"SSLv23", :verify_mode=>1, :ciphers=>"ALL:!ADH:!EXPORT:!SSLv2:RC4+RSA:+HIGH:+MEDIUM:+LOW", :options=>-2147482625}
> #<StringIO:0x007ff6b3d81b50>
> File 'Test Upload CSV' created with id '0B6-mKmKVYdh4ZDhUNS1ULWlKNlk'

**Comment by jostster** [comment] 2017-01-12 21:13
I just ran with the client_config.json specified above and got he same error. I see you are on windows, like me. However, my ciphers are completely different.

```
C:\Ruby23-x64\bin\ruby.exe -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) C:/Users/Brian/RubymineProjects/googletest/bin/rake google_test
{:ssl_version=>"SSLv23", :verify_mode=>1, :ciphers=>"ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-DSS-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:DHE-DSS-AES128-SHA256:DHE-DSS-AES256-SHA256:DHE-DSS-AES128-SHA:DHE-DSS-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:ECDHE-ECDSA-RC4-SHA:ECDHE-RSA-RC4-SHA:RC4-SHA", :options=>-2097019905}
Open the following URL in the browser and enter the resulting code after authorization
https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&client_id=898243283568.apps.googleusercontent.com&include_granted_scopes=true&redirect_uri=urn:ietf:wg:oauth:2.0:oob&response_type=code&scope=https://www.googleapis.com/auth/drive.file
4/6BpzGF<snipped>R7ka9ow
rake aborted!
Faraday::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A
C:/Users/Brian/RubymineProjects/googletest/lib/tasks/google_test.rake:66:in `authorize'
C:/Users/Brian/RubymineProjects/googletest/lib/tasks/google_test.rake:77:in `block in <top (required)>'
-e:1:in `load'
-e:1:in `<main>'
OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A
C:/Users/Brian/RubymineProjects/googletest/lib/tasks/google_test.rake:66:in `authorize'
C:/Users/Brian/RubymineProjects/googletest/lib/tasks/google_test.rake:77:in `block in <top (required)>'
-e:1:in `load'
-e:1:in `<main>'
Tasks: TOP => google_test
(See full trace by running task with --trace)

Process finished with exit code 1
```

**Comment by Fivell** [comment] 2017-01-12 21:18
@jostster , I'm using Mac.

**Comment by jostster** [comment] 2017-01-12 21:20
ahh, so it may be a windows only issue. That sucks because the client only allows windows servers.

**Comment by Fivell** [comment] 2017-01-12 21:23
@jostster , I think it is not activeadmin issue , there is nothing specific to activeadmin in 

```
C:/Users/Brian/RubymineProjects/googletest/lib/tasks/google_test.rake:66:in `authorize'
```

**Comment by jostster** [comment] 2017-01-12 21:29
I would think a config or something from activeadmin is causing something. Removing the activeadmin gem and running the rake google_test it runs fine
```
C:\Ruby23-x64\bin\ruby.exe -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) C:/Users/Brian/RubymineProjects/googletest/bin/rake google_test
{:ssl_version=>"SSLv23", :verify_mode=>1, :ciphers=>"ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-DSS-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:DHE-DSS-AES128-SHA256:DHE-DSS-AES256-SHA256:DHE-DSS-AES128-SHA:DHE-DSS-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:ECDHE-ECDSA-RC4-SHA:ECDHE-RSA-RC4-SHA:RC4-SHA", :options=>-2097019905}
File 'Test Upload CSV' created with id '0B5ifk1cMiDeTNVpseGRudE9ZeTg'. 

Process finished with exit code 0
```

**Comment by timoschilling** [comment] 2017-01-29 18:15
Closed while not reproducible.

**Closed by timoschilling** 2017-01-29 18:15 UTC

**Comment by jostster** [comment] 2017-01-29 19:06
@timoschilling did you try this on a windows environment? it seems to be specific to windows as I was able to duplicate this in the test project i posted above on a windows environment.

**Comment by timoschilling** [comment] 2017-01-30 08:56
@jostster nobody has the time to setup a Windows and a Ruby env to test that. If you can tell what is the problem and how to fix it we can do that. This is an open source project and not a paid software.

I found you issue https://github.com/gimite/google-drive-ruby/issues/239, it looks like Windows has many problems with `Faraday::SSLError`.
