### ISSUE TITLE
3 level drill down on deeply nested forms show page

### ISSUE THREAD

**Issue by wolfieorama** [activeadmin/activeadmin#4333] opened 2016-03-01 09:21 UTC
Hi, 

So I am facing a challenge I have a deeply nested form 3 levels down but so far I am only able to drill down to the second level how do I integrate the show to incorporate all 3 levels drill down ?

appreciated

**Comment by varyonic** [comment] 2017-01-18 18:28
I'm not sure, but this might be resolved by #4618

**Comment by varyonic** [comment] 2017-01-24 22:03
#4618 is now merged.

**Comment by deivid-rodriguez** [comment] 2017-04-27 10:21
Closing due to lack of feedback, feel free to reopen with reproduction steps!

**Closed by deivid-rodriguez** 2017-04-27 10:21 UTC
Labels: question
