### ISSUE TITLE
extract components

### ISSUE THREAD

**Issue by timoschilling** [activeadmin/activeadmin#3571] opened 2014-11-04 20:48 UTC
Change proposal:
I would like to extract some parts of active admin into its one gems to get a cleaner code base.
This a the parts that I want to extract:
- Authorization:
  - CanCan Adapter
  - Pundit Adapter
- Authentication (Devise)
- Comments

The code of the extracted components, can be cleaner through this change. For example comments don't need to life inside the active record orm.

Whats your meaning on this?

**Comment by seanlinsley** [comment] 2015-10-27 20:04
I don't think this is valuable. Active Admin is monolithic, but that in itself isn't bad. If there are some parts that need to be designed better, that can be done without separating them into their own gems.

I think having a ton of add-on gems is a bad idea for the same reason that I think that microservices are a bad idea: code out of sight, is out of mind. Our test suite won't run on it, so we won't know when it breaks. Additionally, having to switch between multiple git repos to read through and understand the code adds extra burden on the reader.

**Comment by pboling** [comment] 2015-10-27 20:10
Well if you provide the integration layer that the external gems plug into then you test that your API on this side does what it needs, and the other can and should be out of sight and out of mind.  It reduces, ideally, the cognitive load required to grok this codebase, because you don't have to deal with as many responsibilities.

Many gems follow this pattern, Rails, Rspec, Devise.  Also nice is with defined plugin APIs other people can build additional plugins for the tool, sort of like I did with React-rails here: https://github.com/pboling/react-rails-benchmark_renderer

**Comment by timoschilling** [comment] 2015-10-27 20:18
@seanlinsley would we really support any decorator gem, any authentication gem, any orm gem, any what ever gem?

**Comment by timoschilling** [comment] 2015-10-28 03:51
Things like https://github.com/activeadmin/activeadmin/pull/4175#issuecomment-151694771 are one reason more, to move adapters out of active admin.

**Comment by seanlinsley** [comment] 2015-10-28 16:07
@pboling I'm not against having an API that lets people easily plug in their own code; that's just good design. But for any gem that meets the qualifications I mention :arrow_double_down:, I'd prefer to keep the integration in this repo.

> @seanlinsley would we really support any decorator gem, any authentication gem, any orm gem, any what ever gem?

If the integration isn't too complex, someone else is willing to write it and open a PR, and it's a common enough gem that more people than the PR author would actually use the integration, I see no reason why it shouldn't be part of Active Admin proper.

> Things like #4175 (comment) are one reason more, to move adapters out of active admin.

No, that was my point: if it's in its own gem, we won't know that it's broken. More often than not there won't be any tests for it. So it's an abandoned gem with no tests. I want to prevent that from happening by keeping the code in a single repo.

**Comment by pboling** [comment] 2015-10-29 00:01
@seanlinsley that is an incredibly pessimistic outlook.  For the record I disagree, but not my repo.

**Comment by seanlinsley** [comment] 2015-10-29 00:26
It's pessimistic to not expect whomever originally wrote the integration to 1) even be aware that it no longer works with new versions, and 2) if they become aware, not have the time to work on it? It seems to happen fairly often. There's plenty of orphaned projects.

But let's say we were to have a large number of integration gems in a place where AA maintainers would have access to fix issues in the future if the original author disappears. Even in that case, we'd have no idea if something was broken until something reported it.

We could get around that by still running tests against those gems from inside the main repo [like we currently do](https://github.com/activeadmin/activeadmin/blob/9005b67e6f2a584f2c0d129b81cbd049a94f0344/Gemfile#L21-L24), but at that point we might as well keep them all inside the same repo.

**Comment by seanlinsley** [comment] 2015-10-29 00:36
This has parallels with the ill-advised practice that a large number of OSS projects on Github have: storing part or all of their documentation in the Github wiki. They do this because it doesn't require PR review to update the documentation, thus lowering the amount of work maintainers have to do.

The problem is, anyone can put ill-advised and completely broken suggestions in the documentation. They can accidentally delete a perfectly good and accurate section. They can delete literally everything there without you knowing.

Sure the wiki is stored in git, so you can go back to before they messed it up. But you 1) need to be aware of the problem and 2) need to have the time to fix it. In my opinion it's better to take a few minutes to review documentation changes via PRs piecemeal, instead of having no idea what the current state of the documentation is.

**Comment by pboling** [comment] 2015-10-29 01:18
> It's pessimistic to not expect whomever originally wrote the integration to 1) even be aware that it no longer works with new versions

I am the author of Rails gems for Rails 1 and 2 that I have not updated for 3, 4, 5.  So what?  If someone else is still using it, and wants to use it on a newer version: it is FOSS.  They can upgrade it themselves, or switch to a better, newer solution.  That's how the system works.  It is not something you (or I, in this case) need to worry about.

> 2) if they become aware, not have the time to work on it? It seems to happen fairly often. There's plenty of orphaned projects.

Again, so what?  Not your problem.  The entire point is that you maintain what you want.  It is incumbent upon the users of FOSS to maintain it if they want to, or move to other solutions if they can't.  It is quite literally not your problem.

> But let's say we were to have a large number of integration gems in a place where AA maintainers would have access to fix issues in the future if the original author disappears. Even in that case, we'd have no idea if something was broken until something reported it.

So what?  If someone reports it then it matters.  If no one reports it, it gathers dust, and eventually dies, then the community has moved on, and is doing other things.  You've effectively reduced the amount of support you have committed to.

Here's a concrete example.  You could support oauth1 inside devise (or active admin).  You could then support oauth2 inside the gem.  You could support them both forever.

Or you break them out into other gems.  If no one uses oauth1 anymore that gem will eventually die, as well it should.  The community will support the oauth2 gem because they use it.

If you want the community to grow and get stronger and more involved then you break things into smaller bits and make interfaces that accept interchangeable parts.  Large successful projects do this.

The point is if you extract things to separate gems, you will have created interfaces that improve the structure of the code and separated concerns.  Others will be able to create integrations to new things.  The community grows and everyone benefits.  You pick which gems you want to support.  Rails spins gems out of core **all the time**.  Some have lived, some have died.  It's no skin off the Rails core team's back when they die.

**Closed** 2023-03-12 22:21 UTC
