### ISSUE TITLE
Use translated Month names for AA datepicker

### ISSUE THREAD

**Issue by timoschilling** [activeadmin/activeadmin#3526] opened 2014-10-28 07:47 UTC

**Comment by deivid-rodriguez** [comment] 2017-04-22 20:31
I think this is a duplicate of #1665, closing!

**Comment by deivid-rodriguez** [comment] 2017-04-22 20:33
Actually @timoschilling considers them different in #3543, so I'm reopening so he can weigh in.

**Closed** 2023-03-12 23:00 UTC
Labels: translation
