### ISSUE TITLE
Index filter as: :string with custom ransacker. It drops the predicate dropdown.

### ISSUE THREAD

**Issue by 50kudos** [activeadmin/activeadmin#4101] opened 2015-08-28 21:20 UTC
In case of using filter as: :string on index page with ransacker defined in a model, it [drops] the predicate dropdown (contains, equals, starts_with, ends_with) which should be independent from the defined ransacker.

I think this [line] probably omit the ransacker condition:
```ruby
def seems_searchable?
  has_predicate? || scope?
end
```
But I can see the way custom ransacker would conflict somehow with the 4 predicates. Let's discuss if any possible way to serve the use case. If there is a strong reason to not bring the dropdown in, i will appreciate and the issue can be closed.
 
[drops]: https://github.com/activeadmin/activeadmin/blob/9c46b14ea0d9b3aaaa3d7520555c9959d06ce7f3/lib/active_admin/inputs/filters/string_input.rb#L14
[line]: https://github.com/activeadmin/activeadmin/blob/9c46b14ea0d9b3aaaa3d7520555c9959d06ce7f3/lib/active_admin/filters/formtastic_addons.rb#L56

**Comment by ball-hayden** [comment] 2015-10-03 15:16
I've also just been bitten by this. I think I'm going to have to monkey-patch my way around it for now...

**Comment by ball-hayden** [comment] 2015-10-03 15:17
This is probably a duplicate of #3409

**Comment by seanlinsley** [comment] 2015-10-27 02:25
Yep, this is a duplicate of #3409

**Closed by seanlinsley** 2015-10-27 02:25 UTC
